-- ============================================================================
-- B0. Enums compartilhados (usados por vários módulos)
-- ============================================================================
CREATE TYPE VLD_ATIVO_INATIVO AS ENUM ('ATIVO', 'INATIVO');
CREATE TYPE VLD_PERIODICIDADE AS ENUM ('MENSAL', 'BIMESTRAL', 'TRIMESTRAL', 'SEMESTRAL', 'ANUAL', 'POR_CICLO', 'NAO_SE_APLICA');

-- ============================================================================
-- B1. Autorização (papel × recurso) + Pessoas
-- ----------------------------------------------------------------------------
-- O gestor configura papéis e os atribui a pessoas existentes (NÃO provisiona
-- contas — isso é do Administrador). Checagem de acesso = papel × recurso.
-- PESSOAS é a tabela fina que liga uma CONTA global a esta incubadora.
-- ============================================================================
CREATE TYPE VLD_NIVEL_PERMISSAO AS ENUM ('TOTAL', 'EDICAO', 'LEITURA', 'NENHUM');
CREATE TYPE VLD_RECURSO AS ENUM (
    'METODOLOGIA', 'PLANEJAMENTO', 'ACOMPANHAR_EXECUCAO', 'EVIDENCIAS_DOCUMENTOS',
    'INDICADORES_METAS', 'APURACAO_INDICADORES', 'EMPREENDIMENTOS', 'USUARIOS');
-- Distingue papel PADRAO (fixo, provido pelo Administrador / vem no seed) de
-- PERSONALIZADO (criado pelo gestor da incubadora). PADRAO não deve ser editado
-- pelo gestor — só atribuído; PERSONALIZADO é totalmente gerido por ele.
CREATE TYPE VLD_TIPO_PAPEL AS ENUM ('PADRAO', 'PERSONALIZADO');

CREATE TABLE IF NOT EXISTS PAPEIS (
    PAP_COD   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME      TEXT NOT NULL,
    TIPO      VLD_TIPO_PAPEL NOT NULL DEFAULT 'PERSONALIZADO',  -- PADRAO = fixo (seed/admin); PERSONALIZADO = criado pelo gestor
    SITUACAO  VLD_ATIVO_INATIVO NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE IF NOT EXISTS PAPEL_PERMISSOES (
    PAP_COD  BIGINT NOT NULL REFERENCES PAPEIS(PAP_COD),
    RECURSO  VLD_RECURSO NOT NULL,
    NIVEL    VLD_NIVEL_PERMISSAO NOT NULL DEFAULT 'NENHUM',
    PRIMARY KEY (PAP_COD, RECURSO)
);

-- Vínculo local de uma CONTA global com esta incubadora. Nome/e-mail vêm de
-- public.CONTAS por join (não duplicados). CTA_COD = ref. fraca cross-schema.
CREATE TABLE IF NOT EXISTS PESSOAS (
    PES_COD   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CTA_COD   BIGINT NOT NULL UNIQUE,                 -- → public.CONTAS (ref. fraca)
    PAP_COD   BIGINT REFERENCES PAPEIS(PAP_COD)      -- papel na incubadora (um por pessoa)
);

-- IDs 1/2/3 vêm da ordem de inserção (identidade inicia em 1).
INSERT INTO PAPEIS (NOME, TIPO)
VALUES ('Gestor da incubadora', 'PADRAO'),
       ('Responsável pelo acompanhamento', 'PADRAO'),
       ('Usuário externo', 'PADRAO');


-- ============================================================================
-- B4. Ciclo
-- ----------------------------------------------------------------------------
-- STATUS (ATIVO/ENCERRADO, edição) × EM_FOCO (o ciclo refletido nas telas).
-- Máx. um ATIVO e um EM_FOCO por incubadora (índices parciais).
-- ============================================================================
CREATE TYPE VLD_STATUS_CICLO AS ENUM ('ATIVO', 'ENCERRADO');
-- enums de EMPREENDIMENTOS (módulo B7), necessários já aqui. Rótulos em ASCII SCREAMING_SNAKE
-- (como os demais enums do schema): o texto amigável fica no front.
CREATE TYPE VLD_ESTAGIO_INCUBACAO AS ENUM ('IDEACAO', 'PRE_INCUBACAO', 'INCUBACAO', 'POS_INCUBACAO');
CREATE TYPE VLD_STATUS_EMPREENDIMENTO AS ENUM ('ATIVO', 'DESLIGADO', 'GRADUADO');
CREATE TYPE VLD_SITUACAO_CONTRATO AS ENUM ('ASSINADO', 'PENDENTE', 'DISTRATO', 'NAO_ASSINADO', 'ENVIADO', 'IRREGULAR', 'FINALIZADO');
CREATE TYPE VLD_NIVEL_MATURIDADE AS ENUM ('IDEACAO', 'VALIDACAO', 'OPERACAO', 'TRACAO', 'ESCALA');
-- ============================================================================
-- B7. Empreendimentos — pessoas do empreendimento
-- ----------------------------------------------------------------------------
-- A tabela EMPREENDIMENTOS está no módulo B4 (por dependência de FK). Aqui só as
-- pessoas do empreendimento (membros da startup; NÃO são usuários do sistema).
-- PRINCIPAL = contato principal perante a incubadora.
-- ============================================================================

CREATE TABLE IF NOT EXISTS CICLOS (
    CIC_COD  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME     TEXT NOT NULL,
    INICIO   DATE,
    FIM      DATE,
    STATUS   VLD_STATUS_CICLO NOT NULL DEFAULT 'ATIVO',    -- ATIVO = edita; ENCERRADO = só consulta
    EM_FOCO  BOOLEAN NOT NULL DEFAULT FALSE                 -- TRUE = ciclo refletido nas telas
);

-- "Um por vez": no máx. um ciclo ATIVO e um EM_FOCO por incubadora.
CREATE UNIQUE INDEX IF NOT EXISTS UQ_CICLO_ATIVO   ON CICLOS (STATUS)  WHERE STATUS = 'ATIVO';
CREATE UNIQUE INDEX IF NOT EXISTS UQ_CICLO_EM_FOCO ON CICLOS (EM_FOCO) WHERE EM_FOCO = TRUE;

-- EMPREENDIMENTOS (módulo B7) — criada aqui por dependência de FK.
CREATE TABLE IF NOT EXISTS EMPREENDIMENTOS (
    EMP_COD             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME                TEXT NOT NULL,
    CNPJ                TEXT,
    CNAE                TEXT,
    ATIVIDADE_ECONOMICA TEXT,
    INSTAGRAM           TEXT,
    SITE                TEXT,
    EMAIL               TEXT,
    SITUACAO_CONTRATO   VLD_SITUACAO_CONTRATO,
    ESTAGIO             VLD_ESTAGIO_INCUBACAO DEFAULT 'IDEACAO',
    STATUS              VLD_STATUS_EMPREENDIMENTO NOT NULL DEFAULT 'ATIVO',
    NIVEL_MATURIDADE    VLD_NIVEL_MATURIDADE,
    ENTRADA             DATE,
    SAIDA               DATE

);

-- DOCUMENTOS_EMPREENDIMENTO (arquivos por empreendimento) é criada adiante, junto de ARQUIVOS
-- (módulo B5), por depender da FK para ARQUIVOS(ARQ_COD).

CREATE TABLE IF NOT EXISTS PESSOAS_EMPREENDIMENTO (
    PSE_COD             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    EMP_COD             BIGINT NOT NULL REFERENCES EMPREENDIMENTOS(EMP_COD),
    NOME                TEXT NOT NULL,
    REPRESENTANTE_LEGAL BOOLEAN NOT NULL DEFAULT FALSE,          -- representante legal
    EMAIL               TEXT,
    TELEFONE            TEXT
);

-- ============================================================================
-- B2. Metodologia CERNE (versionada)
-- ----------------------------------------------------------------------------
-- Metodologia (documento vivo, sem versionamento): PROCESSO → PRATICA / INDICADOR_METODOLOGIA.
-- A árvore é única no schema do tenant e sempre editável; modelos e planos a leem ao vivo.
-- ============================================================================
-- Nível CERNE do processo. Domínio de um valor só ('CERNE_1'): por ora o sistema trata apenas o
-- Nível I; deixa o escopo explícito e reserva espaço para os níveis seguintes.
CREATE TYPE VLD_NIVEL_CERNE AS ENUM ('CERNE_1');

CREATE TABLE IF NOT EXISTS PROCESSOS_METODOLOGIA (
    PRC_COD   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NIVEL     VLD_NIVEL_CERNE NOT NULL DEFAULT 'CERNE_1',
    ORDEM     SMALLINT NOT NULL,
    NOME      TEXT NOT NULL,
    DESCRICAO TEXT,
    SITUACAO  VLD_ATIVO_INATIVO NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE IF NOT EXISTS PRATICAS_METODOLOGIA (
    PRT_COD   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PRC_COD   BIGINT NOT NULL REFERENCES PROCESSOS_METODOLOGIA(PRC_COD),
    ORDEM     SMALLINT NOT NULL,  -- ordem dentro do processo
    NOME      TEXT NOT NULL,
    DESCRICAO TEXT,
    SITUACAO  VLD_ATIVO_INATIVO NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE IF NOT EXISTS INDICADORES_METODOLOGIA (
    INM_COD       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PRT_COD       BIGINT NOT NULL REFERENCES PRATICAS_METODOLOGIA(PRT_COD),
    NOME          TEXT NOT NULL,
    UNIDADE       TEXT,
    PERIODICIDADE VLD_PERIODICIDADE DEFAULT 'NAO_SE_APLICA',
    SITUACAO      VLD_ATIVO_INATIVO NOT NULL DEFAULT 'ATIVO'
);

-- Agrupamentos (sub-planos do Manual) de uma prática: nível entre prática e atividade (ex.: em
-- "Sensibilização": eventos externos, internos, rádio/TV). A atividade referencia AGR_COD (opcional).
CREATE TABLE IF NOT EXISTS AGRUPAMENTOS (
    AGR_COD   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PRT_COD   BIGINT NOT NULL REFERENCES PRATICAS_METODOLOGIA(PRT_COD),
    ORDEM     SMALLINT NOT NULL,  -- ordem dentro da prática
    NOME      TEXT NOT NULL,
    DESCRICAO TEXT,
    SITUACAO  VLD_ATIVO_INATIVO NOT NULL DEFAULT 'ATIVO'
);

-- Atividades-padrão da metodologia (as atividades da incubadora, reaproveitadas a cada ciclo). Sempre
-- ligadas a uma prática (obrigatório; processo deriva dela); AGR_COD (opcional) dá o sub-plano dentro
-- da prática. "Quem"/"quando" NÃO ficam aqui — só no planejamento. Materializadas ao "Gerar do ciclo".
CREATE TABLE IF NOT EXISTS ATIVIDADES_METODOLOGIA (
    AME_COD     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PRT_COD     BIGINT NOT NULL REFERENCES PRATICAS_METODOLOGIA(PRT_COD),
    AGR_COD     BIGINT REFERENCES AGRUPAMENTOS(AGR_COD),  -- sub-plano (opcional)
    ORDEM       SMALLINT NOT NULL,  -- ordem dentro da prática (o app define via proximaOrdem)
    NOME        TEXT NOT NULL,
    OBSERVACOES TEXT,
    POR_EMPREENDIMENTO BOOLEAN NOT NULL DEFAULT FALSE,  -- atividade "da incubada": repete por empreendimento
    SITUACAO    VLD_ATIVO_INATIVO NOT NULL DEFAULT 'ATIVO'
);

-- ----------------------------------------------------------------------------
-- Instância da estrutura por ciclo: o ciclo é dono da sua árvore (chave própria
-- PRCC_COD/PRTC_COD), copiada do template na abertura do ciclo. *_ORIGEM é
-- proveniência fraca (SEM FK) usada só na geração; assim exclusão/inativação no
-- template não alcança ciclos já encerrados. Os filhos (atividades planejadas,
-- indicadores) referenciam PRATICAS_CICLO.
-- ----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS PROCESSOS_CICLO (
    PRCC_COD       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CIC_COD        BIGINT NOT NULL REFERENCES CICLOS(CIC_COD),
    PRC_COD_ORIGEM BIGINT,                       -- proveniência fraca (sem FK)
    NIVEL          VLD_NIVEL_CERNE NOT NULL DEFAULT 'CERNE_1',
    ORDEM          SMALLINT NOT NULL,
    NOME           TEXT NOT NULL,
    DESCRICAO      TEXT
);

CREATE TABLE IF NOT EXISTS PRATICAS_CICLO (
    PRTC_COD       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CIC_COD        BIGINT NOT NULL REFERENCES CICLOS(CIC_COD),
    PRCC_COD       BIGINT NOT NULL REFERENCES PROCESSOS_CICLO(PRCC_COD),
    PRT_COD_ORIGEM BIGINT,                       -- proveniência fraca (sem FK)
    ORDEM          SMALLINT NOT NULL,            -- ordem dentro do processo (copiada do template)
    NOME           TEXT NOT NULL,
    DESCRICAO      TEXT
);

CREATE TABLE IF NOT EXISTS AGRUPAMENTOS_CICLO (
    AGRC_COD       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    CIC_COD        BIGINT NOT NULL REFERENCES CICLOS(CIC_COD),
    PRTC_COD       BIGINT NOT NULL REFERENCES PRATICAS_CICLO(PRTC_COD),
    AGR_COD_ORIGEM BIGINT,                       -- proveniência fraca (sem FK)
    EMP_COD        BIGINT REFERENCES EMPREENDIMENTOS(EMP_COD),  -- grupo dinâmico "por incubada" (nulo nos do template)
    ORDEM          SMALLINT NOT NULL,            -- ordem dentro da prática (copiada do template)
    NOME           TEXT NOT NULL,
    DESCRICAO      TEXT
);

-- Incubadas participantes de um ciclo (definidas ao "Gerar do ciclo"): fonte da duplicação das
-- atividades marcadas "da incubada" por empreendimento.
CREATE TABLE IF NOT EXISTS CICLO_EMPREENDIMENTOS (
    CIC_COD BIGINT NOT NULL REFERENCES CICLOS(CIC_COD),
    EMP_COD BIGINT NOT NULL REFERENCES EMPREENDIMENTOS(EMP_COD),
    PRIMARY KEY (CIC_COD, EMP_COD)
);

-- ============================================================================
-- B4. Planejamento e execução
-- ----------------------------------------------------------------------------
-- ATIVIDADES_PLANEJADAS.EMP_COD a referencia (ordem de FK). Seus enums também.
-- ============================================================================
CREATE TYPE VLD_STATUS_PLANEJAMENTO AS ENUM ('PUBLICADO', 'ENCERRADO');
CREATE TYPE VLD_ORIGEM_ATIVIDADE    AS ENUM ('METODOLOGIA', 'COMPLEMENTAR');
CREATE TYPE VLD_STATUS_ATIVIDADE    AS ENUM ('PLANEJADA', 'EM_ANDAMENTO', 'CONCLUIDA');

CREATE TABLE IF NOT EXISTS PLANEJAMENTOS (
    PLN_COD      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME         TEXT NOT NULL,
    CIC_COD      BIGINT NOT NULL REFERENCES CICLOS(CIC_COD),
    STATUS       VLD_STATUS_PLANEJAMENTO NOT NULL DEFAULT 'PUBLICADO',
    INICIO       DATE,
    FIM          DATE,
    -- progresso (%) e nº de atividades derivam de ATIVIDADES_PLANEJADAS
    RESP_PES_COD BIGINT REFERENCES PESSOAS(PES_COD)     -- responsável do plano → PESSOAS (FK real)
);

CREATE TABLE IF NOT EXISTS ATIVIDADES_PLANEJADAS (
    ATP_COD      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    PLN_COD      BIGINT NOT NULL REFERENCES PLANEJAMENTOS(PLN_COD),
    ORIGEM       VLD_ORIGEM_ATIVIDADE NOT NULL DEFAULT 'METODOLOGIA',
    PRTC_COD     BIGINT NOT NULL REFERENCES PRATICAS_CICLO(PRTC_COD),  -- prática do ciclo (obrigatório)
    AGRC_COD     BIGINT REFERENCES AGRUPAMENTOS_CICLO(AGRC_COD),       -- sub-plano do ciclo (opcional)
    ORDEM        SMALLINT NOT NULL,  -- ordem dentro da prática
    NOME         TEXT NOT NULL,
    OBSERVACOES    TEXT,
    RESP_PES_COD BIGINT REFERENCES PESSOAS(PES_COD),   -- responsável da atividade → PESSOAS (FK real)
    PRAZO        DATE,
    STATUS       VLD_STATUS_ATIVIDADE NOT NULL DEFAULT 'PLANEJADA',
    EMP_COD      BIGINT REFERENCES EMPREENDIMENTOS(EMP_COD)  -- incubada_ref (opcional)
);

-- ============================================================================
-- B5. Evidências e documentos
-- ----------------------------------------------------------------------------
-- Ciclo de vida (uma decisão por versão): PENDENTE_VALIDACAO → VALIDADA (final) | CORRECAO_SOLICITADA.
-- Ao solicitar correção grava-se o MOTIVO na própria versão; corrigir cria a próxima versão. Anexos
-- em ARQUIVOS.
-- ============================================================================
CREATE TYPE VLD_STATUS_EVIDENCIA AS ENUM ('PENDENTE_VALIDACAO', 'VALIDADA', 'CORRECAO_SOLICITADA');

CREATE TABLE IF NOT EXISTS ARQUIVOS (
    ARQ_COD       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME_ORIGINAL TEXT,
    STORAGE_KEY   TEXT,
    CONTENT_TYPE  TEXT,
    TAMANHO_BYTES BIGINT,
    DATA_UPLOAD   TIMESTAMP DEFAULT NOW()
);

-- Documentos (arquivos) de cada empreendimento — módulo B7, criada aqui por depender de ARQUIVOS.
CREATE TABLE IF NOT EXISTS DOCUMENTOS_EMPREENDIMENTO (
    EMP_COD BIGINT NOT NULL REFERENCES EMPREENDIMENTOS(EMP_COD),
    ARQ_COD BIGINT NOT NULL REFERENCES ARQUIVOS(ARQ_COD),
    PRIMARY KEY (EMP_COD, ARQ_COD)
);

CREATE TABLE EVIDENCIAS (
    EVD_COD     BIGINT NOT NULL,     -- id lógico da evidência (repete entre versões)
    EVD_COD_SEQ INT    NOT NULL,     -- versão: 1, 2, 3...
    TITULO      TEXT   NOT NULL,
    ATP_COD     BIGINT NOT NULL REFERENCES ATIVIDADES_PLANEJADAS(ATP_COD),
    ARQ_COD     BIGINT REFERENCES ARQUIVOS(ARQ_COD),
    STATUS          VLD_STATUS_EVIDENCIA NOT NULL DEFAULT 'PENDENTE_VALIDACAO',
    MOTIVO_CORRECAO TEXT,                -- motivo da rejeição (só em CORRECAO_SOLICITADA)
    REG_PES_COD BIGINT REFERENCES PESSOAS(PES_COD),
    DATA        TIMESTAMP DEFAULT NOW(),
    PRIMARY KEY (EVD_COD, EVD_COD_SEQ)
);

CREATE SEQUENCE IF NOT EXISTS SEQ_EVIDENCIA;


-- ============================================================================
-- B6. Indicadores, metas e apuração
-- ----------------------------------------------------------------------------
-- Indicadores do ciclo: gerados da metodologia vigente (METODOLOGIA_CERNE) ou
-- COMPLEMENTAR. Cada meta é uma linha com janela de apuração própria
-- (materializada, ajustável): POR_CICLO ⇒ uma linha cobrindo o ciclo; demais ⇒
-- uma por período. Resultado 1:1 com a meta (MET_COD). Sempre maior-melhor.
-- ============================================================================
CREATE TYPE VLD_ORIGEM_INDICADOR AS ENUM ('METODOLOGIA_CERNE', 'COMPLEMENTAR');

CREATE TABLE IF NOT EXISTS INDICADORES (
    IND_COD       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME          TEXT NOT NULL,
    ORIGEM        VLD_ORIGEM_INDICADOR NOT NULL DEFAULT 'METODOLOGIA_CERNE',
    PRTC_COD      BIGINT REFERENCES PRATICAS_CICLO(PRTC_COD),   -- prática do ciclo (processo deriva dela)
    CIC_COD       BIGINT REFERENCES CICLOS(CIC_COD),
    UNIDADE       TEXT,
    PERIODICIDADE VLD_PERIODICIDADE DEFAULT 'TRIMESTRAL', -- POR_CICLO ⇒ meta global; demais ⇒ por período
    RESP_PES_COD  BIGINT REFERENCES PESSOAS(PES_COD),     -- responsável pela apuração → PESSOAS (FK real)
    SITUACAO      VLD_ATIVO_INATIVO NOT NULL DEFAULT 'ATIVO'
);

CREATE TABLE IF NOT EXISTS INDICADOR_METAS (
    MET_COD     BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    IND_COD     BIGINT NOT NULL REFERENCES INDICADORES(IND_COD),
    VALOR       NUMERIC,
    DATA_INICIO_APURACAO DATE,
    DATA_FIM_APURACAO DATE                                   -- prazo de apuração do período
);

CREATE TABLE IF NOT EXISTS INDICADOR_RESULTADOS (
    MET_COD       BIGINT NOT NULL REFERENCES INDICADOR_METAS(MET_COD) PRIMARY KEY,
    VALOR         NUMERIC,
    REG_PES_COD   BIGINT REFERENCES PESSOAS(PES_COD),  -- quem lançou → PESSOAS (FK real)
    DATA_REGISTRO TIMESTAMP DEFAULT NOW()
);

-- ============================================================================
-- B8. Monitoramento das incubadas
-- ----------------------------------------------------------------------------
-- Dimensões = eixos CERNE (Empreendedor, Tecnologia, Capital, Mercado, Gestão),
-- escala 0–5. Rodada aplica um instrumento; avaliação gera recomendação.
-- ============================================================================
CREATE TYPE VLD_EIXO_CERNE           AS ENUM ('EMPREENDEDOR', 'TECNOLOGIA', 'CAPITAL', 'MERCADO', 'GESTAO');
CREATE TYPE VLD_TIPO_RODADA          AS ENUM ('DIAGNOSTICO_INICIAL', 'PERIODICO');
CREATE TYPE VLD_SITUACAO_RODADA      AS ENUM ('EM_ANDAMENTO', 'CONCLUIDA');
CREATE TYPE VLD_RECOMENDACAO_MONITOR AS ENUM ('CONTINUIDADE', 'REPLANEJAMENTO', 'GRADUACAO', 'DESLIGAMENTO');
CREATE TYPE VLD_STATUS_MONITORAMENTO AS ENUM ('EM_ANDAMENTO', 'CONCLUIDO');

CREATE TABLE IF NOT EXISTS RODADAS_MONITORAMENTO (
    ROD_COD      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    NOME         TEXT NOT NULL,
    TIPO         VLD_TIPO_RODADA NOT NULL DEFAULT 'PERIODICO',
    CIC_COD      BIGINT REFERENCES CICLOS(CIC_COD),
    RESP_PES_COD BIGINT REFERENCES PESSOAS(PES_COD),    -- responsável da rodada → PESSOAS (FK real)
    PRAZO        DATE,
    SITUACAO     VLD_SITUACAO_RODADA NOT NULL DEFAULT 'EM_ANDAMENTO'
);

-- incubadas[] da rodada
CREATE TABLE IF NOT EXISTS RODADA_INCUBADAS (
    ROD_COD  BIGINT NOT NULL REFERENCES RODADAS_MONITORAMENTO(ROD_COD),
    EMP_COD  BIGINT NOT NULL REFERENCES EMPREENDIMENTOS(EMP_COD),
    PRIMARY KEY (ROD_COD, EMP_COD)
);

CREATE TABLE IF NOT EXISTS AVALIACOES_MONITORAMENTO (
    AVA_COD      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ROD_COD      BIGINT NOT NULL REFERENCES RODADAS_MONITORAMENTO(ROD_COD),
    EMP_COD      BIGINT NOT NULL REFERENCES EMPREENDIMENTOS(EMP_COD),
    STATUS       VLD_STATUS_MONITORAMENTO,
    DATA         DATE,
    RECOMENDACAO VLD_RECOMENDACAO_MONITOR,
    OBSERVACAO   TEXT
);

-- pontuacoes{dimensao→0..5}
CREATE TABLE IF NOT EXISTS AVALIACAO_PONTUACOES (
    AVA_COD    BIGINT NOT NULL REFERENCES AVALIACOES_MONITORAMENTO(AVA_COD),
    DIMENSAO   VLD_EIXO_CERNE NOT NULL,
    PONTUACAO  SMALLINT CHECK (PONTUACAO BETWEEN 0 AND 5),
    PRIMARY KEY (AVA_COD, DIMENSAO)
);

-- Matriz papel × recurso (manual, seção 6). NENHUM = "—" (sem acesso).
-- INSERT INTO PAPEL_PERMISSOES (PAP_COD, RECURSO, NIVEL)
-- VALUES
-- -- Gestor da incubadora: Total em tudo
-- (1, 'METODOLOGIA', 'TOTAL'),
-- (1, 'PLANEJAMENTO', 'TOTAL'),
-- (1, 'ACOMPANHAR_EXECUCAO', 'TOTAL'),
-- (1, 'EVIDENCIAS_DOCUMENTOS', 'TOTAL'),
-- (1, 'INDICADORES_METAS', 'TOTAL'),
-- (1, 'APURACAO_INDICADORES', 'TOTAL'),
-- (1, 'EMPREENDIMENTOS', 'TOTAL'),
-- (1, 'USUARIOS', 'TOTAL'),
-- -- Responsável pelo acompanhamento
-- (2, 'METODOLOGIA', 'LEITURA'),
-- (2, 'PLANEJAMENTO', 'LEITURA'),
-- (2, 'ACOMPANHAR_EXECUCAO', 'EDICAO'),
-- (2, 'EVIDENCIAS_DOCUMENTOS', 'EDICAO'),
-- (2, 'INDICADORES_METAS', 'LEITURA'),
-- (2, 'APURACAO_INDICADORES', 'EDICAO'),
-- (2, 'EMPREENDIMENTOS', 'EDICAO'),
-- (2, 'USUARIOS', 'NENHUM'),
-- -- Usuário externo (mentor/consultor/avaliador): só evidências designadas
-- (3, 'EVIDENCIAS_DOCUMENTOS', 'EDICAO');