-- ============================================================================
-- Seed das ATIVIDADES-PADRÃO da metodologia — CERNE 1 (Nível I)
-- Fonte: Manual CERNE I e II (2023), coluna "Atividade"/"Observações" das
-- tabelas de cada prática-chave do Nível I (nomenclatura exata do manual).
-- Regra: atividades DISTINTAS por prática (união dos sub-planos, sem duplicar
-- as idênticas). "Quem" e "quando" NÃO são semeados (só no planejamento). Os
-- fechadores genéricos "Registrar as evidências da execução." e "Realizar
-- avaliação da efetividade das ações praticadas." entram sem observação.
--
-- PRÉ-REQUISITO: rode antes o seed_cerne1_metodologia.sql (as atividades ligam-se
-- às práticas por NOME). USO: no schema do tenant.
--   SET search_path TO "<schema_do_tenant>";
--   \i seed_cerne1_atividades_metodologia.sql
-- As atividades são materializadas no ciclo pelo "Gerar do ciclo" (Metodologia).
-- (Substitui o antigo seed_cerne1_modelo_padrao.sql, agora legado.)
-- ============================================================================

INSERT INTO ATIVIDADES_METODOLOGIA (PRT_COD, NOME, OBSERVACOES) VALUES

-- ===== 1.1 Sensibilização e Prospecção =====================================
-- Sensibilização (eventos externos, internos, rádio/TV, mídias sociais)
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Identificar parceiros externos e caso necessário, firmar parcerias para realização de eventos.',
 'A busca de parcerias pode maximizar o evento em termos de participantes e é estratégico na redução dos custos.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Receber convite.',
 'O processo pode ser iniciado por demanda em fluxo contínuo ou então em datas previstas de acordo com o planejamento semestral.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Mapear e identificar os eventos internos compatíveis com a sensibilização e difusão para a cultura de inovação e empreendedorismo.',
 'O mapeamento e identificação de eventos compatíveis podem maximizar a sensibilização e é estratégico no que diz respeito ao público-alvo.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Receber convocação/indicação ou negociar a participação no evento.',
 'O processo é iniciado por demanda interna em momentos de fluxo contínuo ou então em datas previstas de acordo com o planejamento semestral.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Planejar o evento e os conteúdos.',
 'Padronizar os conteúdos utilizados. Utilizar os próprios incubados, graduados e parceiros como sensibilizadores pode ser uma boa estratégia.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Definir canais de comunicação.',
 'Acompanhar e avaliar os canais utilizados, para assim otimizar os recursos, investindo mais naqueles que trazem melhores resultados.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Definir e reservar todos os recursos necessários para a execução da ação.',
 'Garantir que os recursos estejam disponíveis dentro das especificações do evento; observar recursos financeiros, de infraestrutura, tecnológicos e de logística, sejam eles internos ou dos parceiros.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Divulgar e iniciar inscrições para o evento.',
 'Avaliar o meio de divulgação e a inscrição eletrônica podem ser boas práticas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Receber o convite/pautar a rádio e/ou TV.',
 'Planejar em conjunto com a SUPEC e diretorias da rádio e TV o calendário anual de programas relativos à sensibilização e aproveitar pautas que surgirem fora do planejado.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Definir sensibilizador e assunto.',
 'Padronizar os conteúdos utilizados. Utilizar os próprios incubados e graduados, gestores e pesquisadores como sensibilizadores pode ser uma boa estratégia.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Efetuar a divulgação interna e externa, via mídias sociais.',
 'A prospecção de público para os programas de rádio e TV pode ser feita através das redes sociais do Espaço Empreendedor.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Participar do programa de rádio ou TV.',
 'Apesar do tema proposto, o sensibilizador deverá sempre lembrar de mencionar a incubadora e os serviços ofertados.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Definir pauta de divulgação.',
 'Decidir os temas a serem abordados com ênfase nos acontecimentos e no plano de comunicação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Elaboração do conteúdo/matéria a ser divulgada.',
 'Na criação do conteúdo deve ser considerada a linguagem e identidade visual da Incubadora e o veículo.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Revisão e aprovação do conteúdo a ser divulgado.',
 'Observar o conteúdo e a apropriação ao veículo.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Publicação do conteúdo/matéria nas mídias sociais e/ou site.',
 'O time da publicação é importante para cada tipo de público-alvo e momento.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- Prospecção (bancas do projetão, reuniões com pesquisadores, setores público/privado, curadoria em editais)
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Identificar projetos finais de disciplina que oportunizam negócios e soluções inovadoras.',
 'A equipe de Gestão deve, de forma proativa, prospectar possíveis ofertas inovadoras segundo ideias de negócios que poderão impactar futuramente a economia da área de atuação da incubadora, interagindo com os alunos e os centros das disciplinas de empreendedorismo no decorrer do semestre letivo.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Contatar os docentes da disciplina que será objeto da prospecção e planejar a ação de prospecção.',
 'O registro deste contato inicial pode ser evidência desta prática. O resultado deste contato é o planejamento da ação de prospecção com definição da periodicidade. Este contato pode incluir mais de um contato virtual e/ou físico.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Realizar ação de prospecção no dia da banca final (demoday) e registrar as evidências da execução.',
 'Os registros da ação devem incluir os resultados da execução desta prática-chave.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Armazenar as oportunidades de negócios no Banco de Oportunidades.',
 'Registro que comprova a existência do Banco de Oportunidades. Deve-se demonstrar como foi criado e como se alimenta e atualiza este banco de oportunidades. Deve ser de fácil acesso e fácil compreensão.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Divulgar as oportunidades prospectadas.',
 'Busca fazer um matchmaking casando ofertantes com demandantes ou vice-versa. Apresentar as oportunidades que possam ser aproveitadas por interessados e que talvez possam se tornar empreendedores da incubadora.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Identificar grupos de pesquisas e laboratórios com potenciais projetos de inovação com capacidade de geração de negócios.',
 'A equipe de Gestão deve, de forma proativa, prospectar possíveis ofertas inovadoras segundo ideias de negócios que poderão impactar futuramente a economia da área de atuação da incubadora.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Contatar os grupos de pesquisa e docentes que serão objeto da prospecção e planejar a ação de prospecção.',
 'O registro deste contato inicial pode ser evidência desta prática. O resultado deste contato é o planejamento da ação de prospecção com definição da periodicidade. Este contato pode incluir mais de um contato virtual e/ou físico.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Prospectar ideias através de reuniões e rodas de conversas, previamente agendadas com a Equipe Gestora.',
 'Os registros da ação devem incluir os resultados da execução desta prática-chave.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Identificar parceiros/atores com demandas/gargalos setoriais tanto no setor público quanto privado.',
 'Ação proativa; é corpo a corpo. A equipe de gestão deve buscar oportunidades de negócio. Pode convidar empresas para que exponham seus problemas e/ou necessidades, que poderão ser ideias de negócios.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Definir canais de comunicação com os parceiros.',
 'Acompanhar e avaliar os canais utilizados, para assim otimizar os recursos, investindo mais naqueles que trazem melhores resultados.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Contatar o parceiro que será objeto da prospecção e planejar a ação de prospecção.',
 'O registro deste contato inicial pode ser evidência desta prática. O resultado deste contato é o planejamento da ação de prospecção com definição da periodicidade.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Realizar ação de prospecção e registrar as evidências da execução.',
 'Os registros da ação devem incluir os resultados da execução desta prática-chave.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Identificar editais e/ou chamadas com demandas e possibilidades de negócios.',
 'Ação proativa. A equipe de gestão deve buscar oportunidades de negócio em editais e chamadas publicadas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Realizar a curadoria das chamadas e editais de acordo com a vocação da incubadora, e em consonância com os negócios incubados, graduados ou prospectados.',
 'Acompanhar e avaliar os canais utilizados, para assim otimizar os recursos, investindo mais naqueles que trazem melhores resultados.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- Qualificação de Potenciais Empreendedores (disciplinas da universidade, eventos internos)
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Mapear e identificar as disciplinas de empreendedorismo e inovação compatíveis com a qualificação de potenciais empreendedores.',
 'Padronizar os conteúdos utilizados. Utilizar a própria equipe de gestão, os incubados e/ou graduados como facilitadores pode ser uma boa estratégia. Se utilizar ações de terceiros, demonstrar claramente a parceria e que a mesma está em sintonia com os objetivos da incubadora.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Negociar com os docentes a participação e o conteúdo a ser desenvolvido.',
 'Negociar os quesitos a serem abordados na ótica de otimização do aprendizado, em complemento à disciplina.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Mapear e identificar os eventos internos compatíveis para a qualificação de potenciais empreendedores.',
 'O mapeamento e identificação de eventos compatíveis podem maximizar a qualificação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Receber convocação/indicação ou negociar a participação no evento.',
 'O processo é iniciado por demanda interna em momentos de fluxo contínuo ou então em datas previstas de acordo com o planejamento semestral.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Planejar o evento, os instrumentos e os conteúdos de qualificação.',
 'Padronizar os conteúdos utilizados. Utilizar os próprios incubados, graduados e parceiros como sensibilizadores pode ser uma boa estratégia.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Definir e reservar todos os recursos necessários para a execução da ação.',
 'Garantir que os recursos estejam disponíveis dentro das especificações do evento; observar recursos financeiros, de infraestrutura, tecnológicos e de logística.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Divulgar e iniciar inscrições para o evento.',
 'Avaliar o meio de divulgação e a inscrição eletrônica podem ser boas práticas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Realizar ação e registrar as evidências da execução.',
 'Os registros da ação devem incluir pelo menos o número e perfil das pessoas qualificadas, o local, a data, profissional responsável e o conteúdo apresentado.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- ===== 1.2 Seleção =========================================================
-- Recepção de Propostas
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Planejar processo de Seleção.',
 'Definir o tipo de chamada, etapas do processo, os formulários e as ferramentas para recepção de propostas, formas de submissão. Definir os critérios de avaliação. Definir como e quando a chamada será lançada.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Elaborar instrumento de chamada / Edital.',
 'Colocar nele todo o definido no planejamento anterior; deixar claras as etapas do processo, os instrumentos/documentos a serem apresentados, os critérios de avaliação, a forma de apresentar as propostas e o cronograma completo.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Definir canais de comunicação e divulgação.',
 'Acompanhar e avaliar os canais utilizados, para assim otimizar os recursos, investindo mais naqueles que trazem melhores resultados.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Divulgar chamada de candidatos à incubação.',
 'Avaliar o meio de divulgação é uma boa prática.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Receber propostas.',
 'Ter todas as propostas registradas/protocoladas como recebidas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Efetuar a homologação das propostas.',
 'Avaliar, de acordo com a chamada, se cumpriram os requisitos formais da submissão, não avaliando aqui o conteúdo da proposta em si.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Informar e registrar aquelas propostas eliminadas.',
 'Todas as propostas que não forem aceitas por não cumprir requisitos da submissão serão registradas e eliminadas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Divulgar resultado da recepção de propostas.',
 'Registrar e protocolar aquelas propostas OK e que serão avaliadas na próxima prática-chave.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- Avaliação (avaliação de duas etapas)
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Planejar a Avaliação.',
 'A partir do Planejamento do processo de seleção definido na prática-chave recepção de propostas, e da chamada/Edital, definir em maiores detalhes todas as ações do procedimento de avaliação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Convidar Avaliadores.',
 'Definir o meio de contato e convite, levando em consideração expertise e perfil do potencial avaliador; enviar informações sobre o processo de avaliação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Formar a Banca de Avaliação.',
 'Convocar os membros respeitando os prazos previstos na chamada/Edital. Mínimo dois integrantes.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Preparar a Avaliação e alinhar com a banca de avaliação, entregando instrumentos de avaliação.',
 'Seria interessante fazer uma reunião com os avaliadores para mostrar as expectativas e objetivos da incubadora, processo de seleção, critérios de avaliação, pesos dos mesmos, etc. Preparar e entregar todos os documentos e formulários necessários para avaliação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Enviar propostas à Banca e promover uma leitura criteriosa.',
 'Confirmar que receberam as propostas, reforçar os critérios e os prazos. Importante: comprovar que todas as propostas recebidas serão avaliadas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Executar as etapas de avaliação previstas na chamada/Edital.',
 'Seguir rigorosamente todo o processo planejado e definido na chamada/edital: cronogramas, etapas, instrumentos utilizados.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Consolidar as avaliações da Banca.',
 'Tabular todas as avaliações, promover consenso entre os membros da banca, elaborar lista de aprovados, de reprovados e os motivos da reprovação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Entrar em contato com os proponentes, informar resultados e motivos de propostas não aprovadas.',
 'Após a consolidação, a incubadora deve entrar em contato com os proponentes, antes de tornar público o resultado, para informá-los se o projeto foi ou não aprovado e justificar o motivo da não aprovação, orientando-os sobre possíveis melhorias na proposta.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Divulgar resultado do processo seletivo.',
 'Fazer lista para oficializar o resultado da seleção, divulgando nos meios apropriados.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- Contratação (assinatura contrato de incubação)
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Planejar a Contratação definindo datas e convidando as autoridades e empreendimentos selecionados.',
 'A partir do Planejamento do processo de seleção definido na prática-chave recepção de propostas, e da chamada/Edital, definir em maiores detalhes todas as ações do procedimento de contratação. Verificar cronograma.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Realizar encontro/reunião para orientação sobre contratação e incubação.',
 'Explicar o processo de contratação e de incubação. Entregar lista de documentos necessários para contratação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Receber todos os documentos para contratação.',
 'Verificar se todos os documentos solicitados foram entregues e se estão em conformidade.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Elaborar Contrato e envio aos empreendedores e ao setor jurídico.',
 'De acordo com o tipo de processo de incubação (pré, virtual, residente). Instrumento formal que estabeleça as regras e responsabilidades entre o candidato e a incubadora. Deve conter todas as condições da relação entre o empreendedor e a incubadora.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Revisão jurídica e por parte dos empreendedores dos contratos.',
 'Revisar, tirar as dúvidas e chegar a um acordo para assinatura. Confirmar data de assinatura.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Realizar evento de Assinatura dos contratos e registrar as evidências da execução.',
 'Grande momento; divulgar amplamente, envolver parceiros, incubados, graduados, equipe da incubadora e mantenedora. Pode-se entregar certificado de incubado.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Realizar integração dos novos incubados e registrar as evidências da execução.',
 'Apresentar incubadora, equipe, outros incubados, visita guiada aos ambientes. Boa oportunidade para ampliar a interação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- ===== 1.3 Desenvolvimento do Empreendimento ===============================
-- Planejamento do Empreendimento
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Identificar se é planejamento inicial (A) ou atualização de planejamento já existente (B).',
 'Importante verificar no início do procedimento se é o planejamento inicial de um novo incubado ou a atualização do planejamento de um incubado após executar monitoramento. O processo de planejamento deve ser sistemático; não deve ser feito apenas na entrada da empresa/empreendedor na incubadora.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 '(A) Definir e elaborar os instrumentos e modelos que auxiliarão o planejamento e o monitoramento.',
 'O formato e a profundidade do plano são definidos pela incubadora. Podem ser utilizadas diferentes metodologias e modelos de planos. Aqui também devem ser definidos os instrumentos que serão utilizados no monitoramento, pois esta dupla planejamento/acompanhamento é definida aqui.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 '(A) Marcar encontro inicial com empreendedor para alinhamento e conhecimento dos instrumentos.',
 'O responsável deve agendar reunião com as empresas recém-incubadas para realização do alinhamento, explicar a metodologia de planejamento, seus instrumentos e modelos de documentos nos 5 eixos.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Elaborar o Planejamento.',
 'O planejamento do empreendimento deve estabelecer ações que iniciam um ciclo de desenvolvimento. A gestão do planejamento deve ser do empreendedor. O planejamento deve conter um conjunto de estratégias, metas e ações para o curto, médio e longo prazo.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Aprovar o planejamento proposto.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 '(B) Utilizar monitoramento para atualizar o planejamento.',
 'Os planos devem ser atualizados de acordo com o desenvolvimento do negócio identificado no monitoramento.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 '(B) Aprovar planejamento modificado e iniciar acompanhamento da execução.',
 'A atualização dos planos alimenta o desenvolvimento de ações da incubadora. Os planos devem ser utilizados como ferramentas de gestão.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- Agregação de Valor
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'A partir dos planejamentos dos incubados, elaborar o Plano Anual de Agregação de Valor da Incubadora.',
 'O plano anual deve ser elaborado de forma coletiva, envolvendo toda a equipe do Espaço Empreendedor, sua Gerência e a equipe da Diretoria de Inovação Tecnológica, com base no planejamento estratégico e na metodologia de boas práticas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'A partir do Plano Anual de Agregação de Valor, identificar a ação de agregação de valor a ser executada (a que a incubadora irá oferecer).',
 'Há dois momentos em que a incubadora deve decidir quais ações de agregação de valor devem ser desenvolvidas para as empresas: 1. no momento do planejamento inicial; 2. sempre após um monitoramento, pois os planejamentos podem ser atualizados e, por isso, deve ser novamente executado este procedimento para verificar se há novas necessidades de ações de agregação de valor.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Identificar e contatar os prestadores do serviço de agregação de valor.',
 'Podem ser internos, externos ou identificar parceiros que possam executar estas ações de agregação de valor.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Realizar a ação de agregação de valor e registrar as evidências da execução.',
 'Os registros da ação devem incluir todas as informações para identificar a execução da ação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Atualizar os planos dos incubados participantes.',
 'Atualizar em cada planejamento do incubado a ação realizada, com os resultados obtidos.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- Monitoramento do Empreendimento
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Identificar e definir os especialistas que farão o monitoramento (equipe de gestão ou mentor ou professor).',
 'Podem ser internos, externos ou identificar parceiros que possam executar a consultoria. Quando utilizar profissionais externos à incubadora, esta relação deve ser formalizada.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Elaborar, verificar e divulgar Agenda de Monitoramentos.',
 'A partir dos planejamentos dos incubados, elaborar cronograma de monitoramento.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Entrevista/Encontro com os empreendedores.',
 'Nesta reunião, utilizar os instrumentos de monitoramento para coletar as informações referentes ao estágio dos 5 eixos. É uma verificação do previsto vs. realizado no planejamento do empreendimento.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Analisar situação e evolução da empresa, segundo metas e critérios do planejamento.',
 'Verificar o desempenho do empreendimento em relação ao planejado nos 5 eixos.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Avaliar resultados obtidos.',
 'Avaliar os resultados de acordo com as metas previstas para a etapa e estágio atual do empreendimento.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Elaborar relatório do monitoramento.',
 'Utilizar instrumento para elaborar relatório com todas as considerações do monitoramento, como por exemplo recomendação para graduação, sugestões para replanejamento (com novas ações, prazos e metas, com justificativas) ou recomendação de desligamento.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Reunião com empreendedor para avaliar relatório.',
 'Análise das informações fornecidas pelo relatório, levando em consideração o tipo de negócio e o estágio de incubação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Atualizar os planos dos incubados participantes.',
 'Atualizar em cada planejamento do incubado as informações referentes ao monitoramento, resultados obtidos, metas atingidas, não atingidas e próximos passos.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Verificar se o empreendimento está pronto para graduar, para continuar incubado ou para ser desligado.',
 'Se atingiu o grau de maturidade para graduar, ir para a prática-chave graduação; se vai continuar incubado, ir para a prática-chave planejamento para atualizar seu planejamento a partir deste monitoramento; se não vai continuar incubado, fazer o desligamento.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- ===== 1.4 Graduação e Relacionamento com Graduados ========================
-- Graduação (evento de graduação)
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Identificar no monitoramento e no Plano Anual de Graduações as empresas incubadas que estão aptas para graduar.',
 'A partir dos planejamentos atualizados pelos monitoramentos, identificar as empresas que estarão aptas para graduar no próximo ciclo.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Avaliar e confirmar condições para a mudança de status da empresa.',
 'A partir da recomendação de graduação apontada no último monitoramento e registrada no planejamento da incubada, avaliar o empreendimento para graduação e gerar um Relatório de Graduação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Preparar empresa para Graduação.',
 'Reunião para esclarecimentos. Auxiliar a empresa na estimativa do impacto financeiro e econômico da graduação. Auxiliar na procura de espaço físico para sua instalação como graduada.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Realizar Procedimentos administrativos para a Graduação.',
 'Atualizar todos os registros internos da incubadora (de incubada para graduada). Fazer vistoria da sala e móveis.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Oficializar Juridicamente a Graduação.',
 'Preparar e assinar o termo de encerramento de graduação. Preparar contrato de associado graduado. Devolução de chaves.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Planejar Cerimônia de Graduação.',
 'Identificar a mesa de honra, convidar, confeccionar certificados de graduação, elaborar convite eletrônico e/ou impresso. Identificar disponibilidade financeira para definir o tipo de evento a ser realizado.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Divulgar Cerimônia de graduação.',
 'Solicitar à assessoria de comunicação a divulgação. Enviar os convites. Avaliar meios de divulgação. Verificar pessoas a serem convidadas para graduação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Realizar a Cerimônia de graduação e registrar as evidências.',
 'Na cerimônia deverão ser convidadas autoridades da Instituição e do mercado e, se possível, clientes e parceiros das empresas graduadas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- Relacionamento com Graduados (acompanhamento da evolução, oferta de serviços)
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Elaborar/atualizar instrumentos do acompanhamento do graduado.',
 'O formato e a profundidade do acompanhamento são definidos pela incubadora. Podem ser utilizadas diferentes metodologias e modelos. Importante acompanhar a evolução do empreendimento após a sua graduação.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Enviar instrumento aos graduados.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Receber instrumento preenchido e consolidar num relatório de desempenho dos graduados.',
 'Verificar o desempenho do empreendimento em relação ao tempo transcorrido. Verificar pontos fortes, fracos, ameaças e oportunidades. Representação gráfica da evolução dos graduados. Utilizar instrumento para elaborar relatório com todas as considerações do acompanhamento, como por exemplo recomendação para novos serviços, oportunidades de parcerias, etc.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Divulgar resultados do acompanhamento.',
 'Divulgar nos meios apropriados o estágio atual, a evolução e os resultados obtidos pelos graduados.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Identificar nas respostas do formulário os serviços sugeridos pelos graduados.',
 'Elaborar mix de serviços, com foco nas graduadas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Identificar quais serviços podem ser oferecidos pela incubadora.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Divulgar portfólio de serviços para graduados e empresas em geral.',
 'Divulgação ampla.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Receber demandas por execução de serviços.',
 'Daqui em diante é outra linha do tempo.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Planejar a execução do serviço.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Executar o serviço.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Registrar as evidências da execução.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- ===== 1.5 Gerenciamento Básico ============================================
-- Estrutura Organizacional
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Solicitar/atualizar documentos que comprovam existência da incubadora.',
 'Caso a incubadora não tenha CNPJ próprio, deve haver um documento que comprove sua existência e vinculação com a entidade gestora/mantenedora. Formalização da incubadora como um programa da instituição mantenedora.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Criar/atualizar comprovação da existência da equipe.',
 'Um membro com 40 horas de dedicação à incubadora.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Criar/atualizar Modelo de Negócios da Incubadora.',
 'Desenvolver um Modelo de Negócios da incubadora, mantendo-o atualizado.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Criar/atualizar Plano de Ação.',
 'Utilizar o plano de ação como referência na implementação das ações propostas para atingir metas e objetivos.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Arquivar todos os documentos da Estrutura Organizacional.',
 'Escolher os meios de armazenamento. Lembrar que os documentos devem estar assinados. A escolha do meio de arquivamento deve permitir fácil consulta, pois vários destes documentos são utilizados por outras práticas-chave.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- Operação da Incubadora (gestão financeira, infraestrutura física/tecnológica, serviços operacionais)
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'No início de cada ano, elaborar o Orçamento Anual e o Fluxo de Caixa (previsto).',
 'Elaborar orçamento, fluxo de caixa e plano de sustentabilidade. Devem ser explicitados todos os apoios recebidos, as ações e estruturas mantidas com recursos próprios e as estratégias para garantir a sustentabilidade.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Mensalmente, fazer todos os controles financeiros e atualizar o fluxo de caixa com o realizado.',
 'Atualizar o fluxo de caixa semanalmente ou mensalmente com controle do previsto/realizado. A incubadora precisa ter um controle sobre as receitas e despesas, tanto financeiras quanto econômicas.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'No final do ano, fazer uma análise do orçamento e do fluxo de caixa e, a partir desta análise, elaborar o plano de sustentabilidade financeira para o próximo ano.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Levantar necessidades de Infraestrutura Física e Tecnológica.',
 'Ouvir incubados, graduados, equipe de gestão e parceiros sobre a adequação das atuais instalações físicas e tecnológicas e novas necessidades.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Elaborar/Atualizar Documento descrevendo Infraestrutura Física e Tecnológica.',
 'Espaços para empreendimentos, espaços comuns, espaços para reuniões e eventos, área para convivência, equipamentos para aluguel, infraestrutura de comunicação (internet, telefone etc.). Importante prever área de convivência (cafezinho) e área para showroom.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Mensalmente, verificar se a infraestrutura física e tecnológica está de acordo com as atividades desenvolvidas na incubadora.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Anualmente, fazer as adequações previstas na infraestrutura física e tecnológica.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Definir os Serviços Operacionais necessários para a incubadora.',
 'Definir tipo de limpeza, tipo de vigilância, tipos necessários de manutenção e necessidades e atividades na recepção da incubadora.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Atualizar o documento que descreve os serviços operacionais.',
 'Definir periodicidade do serviço. Tipo de vigilância, horários da vigilância, formas de acesso, uso de crachá, leitoras de digitais, etc. Tipos de equipamentos para manutenção preventiva e para manutenção corretiva.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Mensalmente, verificar se os serviços operacionais estão sendo oferecidos de acordo com o previsto.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Arquivar todos os documentos da Operação da Incubadora.',
 'Escolher os meios de armazenamento. A escolha do meio de arquivamento deve permitir fácil consulta, pois vários destes documentos são utilizados por outras práticas-chave.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL),

-- Comunicação e Marketing (material de comunicação, estratégia de presença digital)
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'Desenvolver identidade corporativa.',
 'Definir missão, visão e valores; criar logomarca e manual de uso da marca; criar assinaturas de e-mail. A incubadora preocupa-se com a formatação das mensagens enviadas através de seu e-mail corporativo.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'Desenvolver e manter atualizado material de comunicação impresso e digital.',
 'Desenvolver peças gráficas: cartões de visita, envelopes, papel timbrado, folder institucional, crachás.'),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'No início de cada ano, elaborar a estratégia de presença digital da incubadora.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'Executar a estratégia de presença digital.', NULL),
((SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'Realizar avaliação da efetividade das ações praticadas.', NULL);
