-- ============================================================================
-- LEGADO — não é mais carregado na criação do tenant (ver TenantSchemaProvisioner).
-- Substituído por seed_cerne1_atividades_metodologia.sql: com a unificação de
-- modelo e metodologia, as atividades passaram a viver em ATIVIDADES_METODOLOGIA.
-- Mantido apenas para referência histórica.
-- ============================================================================
-- Seed do MODELO PADRÃO de planejamento — CERNE 1 (Nível I)
-- Fonte: Manual CERNE I e II (2023), colunas "Atividade" e "Observações" das
-- práticas-chave do Nível I. As colunas "Quem" e "Quando" NÃO são semeadas:
-- responsável (RESP_PES_COD) e prazo são definidos apenas no planejamento.
--
-- PRÉ-REQUISITO: rode antes o seed_cerne1_metodologia.sql (as atividades ligam-se
-- às práticas por NOME). USO: no schema do tenant.
--   SET search_path TO "<schema_do_tenant>";
--   \i seed_cerne1_modelo_padrao.sql
-- O modelo nasce RASCUNHO; publique-o pela tela de Modelos para gerar planos.
-- ============================================================================

INSERT INTO MODELOS (NOME, PERIODICIDADE, DESCRICAO) VALUES
    ('Plano Anual CERNE 1 (padrão)', 'ANUAL',
     'Modelo padrão de planejamento anual com as atividades-chave das práticas do CERNE 1 (Manual CERNE I e II). Observações conforme o manual; responsável e prazo definidos no planejamento.');

-- Atividades do modelo (MOD_COD e PRT_COD resolvidos por NOME)
INSERT INTO ATIVIDADES_MODELO (MOD_COD, PRT_COD, NOME, OBSERVACOES) VALUES

-- ===== 1.1 Sensibilização e Prospecção =====================================
-- Sensibilização
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Identificar eventos e parceiros e firmar parcerias',
 'Mapear eventos internos e externos, programas de rádio/TV e pautas de mídias sociais compatíveis com a sensibilização. A busca de parcerias pode maximizar o alcance e reduzir custos.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Planejar o evento/ação e os conteúdos',
 'Padronizar os conteúdos utilizados. Utilizar os próprios incubados, graduados e parceiros como sensibilizadores pode ser uma boa estratégia.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Definir canais de comunicação e divulgar',
 'Acompanhar e avaliar os canais utilizados para otimizar os recursos. Avaliar o meio de divulgação e a inscrição eletrônica.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Definir e reservar os recursos necessários',
 'Garantir recursos financeiros, de infraestrutura, tecnológicos e de logística, sejam internos ou dos parceiros.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Executar a ação e registrar as evidências',
 'Registrar número e perfil das pessoas sensibilizadas, local, data, responsável e conteúdo. Perguntar se há interesse em incubar (entrada para a prática de Qualificação).'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Sensibilização'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- Prospecção
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Identificar oportunidades de negócio',
 'Ação proativa: bancas/projetão, grupos de pesquisa e laboratórios, setores público e privado, editais e chamadas. Prospectar ofertas inovadoras e demandas setoriais que possam gerar negócios.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Contatar o objeto da prospecção e planejar a ação',
 'O registro do contato inicial pode ser evidência da prática. O resultado é o planejamento da ação de prospecção com definição da periodicidade.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Realizar a ação de prospecção e registrar as evidências',
 'Os registros da ação devem incluir os resultados da execução desta prática-chave.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Armazenar as oportunidades no Banco de Oportunidades',
 'Demonstrar como o banco é criado, alimentado e atualizado. Deve ser de fácil acesso e fácil compreensão.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Divulgar as oportunidades prospectadas',
 'Matchmaking: casar ofertantes e demandantes, apresentando as oportunidades a interessados que possam se tornar empreendedores da incubadora.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Prospecção'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- Qualificação de Potenciais Empreendedores
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Mapear disciplinas e eventos compatíveis com a qualificação',
 'Utilizar a própria equipe de gestão, incubados e/ou graduados como facilitadores. Demonstrar claramente as parcerias quando houver ações de terceiros.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Negociar a participação e o conteúdo com docentes/organizadores',
 'Negociar os quesitos a serem abordados na ótica de otimização do aprendizado, em complemento à disciplina/evento.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Definir e reservar os recursos necessários',
 'Recursos financeiros, de infraestrutura, tecnológicos e de logística.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Realizar a ação de qualificação e registrar as evidências',
 'Registrar número e perfil das pessoas qualificadas, local, data, responsável e conteúdo apresentado.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- ===== 1.2 Seleção =========================================================
-- Recepção de Propostas
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Planejar o processo de seleção',
 'Definir o tipo de chamada, etapas, formulários, ferramentas e formas de submissão; definir os critérios de avaliação e quando a chamada será lançada.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Elaborar o instrumento de chamada/Edital',
 'Deixar claras as etapas, os documentos a apresentar, os critérios de avaliação, a forma de apresentar as propostas e o cronograma completo.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Definir canais de comunicação e divulgar a chamada',
 'Acompanhar e avaliar os canais para otimizar os recursos. Avaliar o meio de divulgação é uma boa prática.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Receber e homologar as propostas',
 'Registrar/protocolar as propostas recebidas e avaliar o cumprimento dos requisitos formais da submissão (sem avaliar o conteúdo da proposta em si).'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Registrar propostas eliminadas e divulgar o resultado da recepção',
 'Propostas que não cumprirem os requisitos são registradas e eliminadas; protocolar as aptas, que serão avaliadas na próxima prática-chave.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Recepção de Propostas'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- Avaliação
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Planejar a avaliação',
 'A partir do planejamento da seleção e da chamada/Edital, detalhar todas as ações do procedimento de avaliação.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Convidar avaliadores e formar a banca de avaliação',
 'Considerar expertise e perfil dos avaliadores. Convocar respeitando os prazos da chamada/Edital (mínimo de dois integrantes).'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Preparar a avaliação e alinhar com a banca',
 'Apresentar expectativas, critérios e pesos; preparar e entregar os instrumentos e formulários necessários para a avaliação.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Enviar as propostas e executar as etapas de avaliação',
 'Seguir rigorosamente o processo definido na chamada/Edital. Comprovar que todas as propostas recebidas serão avaliadas.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Consolidar as avaliações e informar os proponentes',
 'Promover consenso entre os membros da banca; contatar os proponentes antes da divulgação, justificando as propostas não aprovadas.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Divulgar o resultado do processo seletivo',
 'Oficializar o resultado da seleção, divulgando nos meios apropriados.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Avaliação'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- Contratação
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Planejar a contratação',
 'Definir datas e convidar as autoridades e os empreendimentos selecionados; verificar o cronograma.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Orientar sobre a contratação e receber os documentos',
 'Explicar o processo de contratação e de incubação; entregar e conferir a lista de documentos necessários.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Elaborar o contrato de incubação e revisar juridicamente',
 'Conforme o tipo de incubação (pré, virtual, residente). Estabelecer as regras e responsabilidades entre o empreendedor e a incubadora.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Realizar o evento de assinatura e registrar as evidências',
 'Divulgar amplamente; envolver parceiros, incubados, graduados, equipe e mantenedora. Pode-se entregar certificado de incubado.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Realizar a integração dos novos incubados',
 'Apresentar a incubadora, a equipe, os demais incubados e os ambientes. Boa oportunidade para ampliar a interação.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Contratação'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- ===== 1.3 Desenvolvimento do Empreendimento ===============================
-- Planejamento do Empreendimento
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Identificar se é planejamento inicial ou atualização',
 'O planejamento deve ser sistemático, não apenas na entrada do empreendimento na incubadora.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Definir os instrumentos e modelos de planejamento e monitoramento',
 'O formato e a profundidade são definidos pela incubadora. A dupla planejamento/monitoramento é definida aqui.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Realizar o encontro inicial de alinhamento com o empreendedor',
 'Explicar a metodologia de planejamento, seus instrumentos e modelos nos 5 eixos: empreendedor, tecnologia, capital, mercado e gestão.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Elaborar e aprovar o planejamento do empreendimento',
 'A gestão do planejamento é do empreendedor. Deve conter estratégias, metas e ações de curto, médio e longo prazo.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Atualizar o planejamento a partir do monitoramento',
 'Os planos são atualizados conforme o desenvolvimento identificado no monitoramento e usados como ferramenta de gestão.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Planejamento do Empreendimento'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- Agregação de Valor
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Elaborar o Plano Anual de Agregação de Valor',
 'Elaborar de forma coletiva, envolvendo a equipe, com base no planejamento estratégico e na metodologia de boas práticas.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Identificar a ação de agregação de valor a ser executada',
 'Definir no momento do planejamento inicial e sempre após um monitoramento, verificando novas necessidades das empresas.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Identificar e contatar os prestadores do serviço',
 'Podem ser internos, externos ou parceiros que executem as ações de agregação de valor.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Realizar a ação de agregação de valor e registrar as evidências',
 'Os registros devem incluir todas as informações para identificar a execução da ação.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Atualizar os planos dos incubados participantes',
 'Registrar a ação realizada e os resultados obtidos em cada planejamento do incubado.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Agregação de Valor'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- Monitoramento do Empreendimento
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Definir os especialistas e elaborar a agenda de monitoramentos',
 'Especialistas internos, externos ou parceiros (formalizar quando externos). Elaborar o cronograma a partir dos planejamentos dos incubados.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Realizar a entrevista/encontro com os empreendedores',
 'Usar os instrumentos de monitoramento para coletar informações dos 5 eixos: verificação do previsto vs. realizado no planejamento.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Analisar a situação e avaliar os resultados obtidos',
 'Verificar o desempenho do empreendimento em relação às metas e critérios do planejamento nos 5 eixos.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Elaborar o relatório do monitoramento',
 'Considerações do monitoramento: recomendação de graduação, sugestões de replanejamento com novas ações/prazos/metas ou recomendação de desligamento.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Atualizar os planos e definir o encaminhamento do empreendimento',
 'Atualizar resultados e próximos passos. Verificar se está pronto para graduar, se continua incubado ou se será desligado.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Monitoramento do Empreendimento'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- ===== 1.4 Graduação e Relacionamento com Graduados ========================
-- Graduação
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Identificar as empresas aptas para graduar',
 'A partir dos planejamentos atualizados pelos monitoramentos e do Plano Anual de Graduações, identificar as empresas aptas no próximo ciclo.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Avaliar e confirmar as condições para a mudança de status',
 'A partir da recomendação de graduação do último monitoramento, avaliar o empreendimento e gerar um Relatório de Graduação.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Preparar a empresa para a graduação',
 'Auxiliar na estimativa do impacto financeiro e econômico da graduação e na procura de espaço físico para a instalação como graduada.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Realizar os procedimentos administrativos e oficializar juridicamente',
 'Atualizar os registros (de incubada para graduada), termo de encerramento, contrato de associado graduado e devolução de chaves.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Planejar, divulgar e realizar a cerimônia de graduação',
 'Confeccionar certificados; convidar autoridades, mercado, clientes e parceiros; registrar as evidências da cerimônia.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Graduação'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- Relacionamento com Graduados
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Elaborar/atualizar os instrumentos de acompanhamento dos graduados',
 'O formato é definido pela incubadora. Importante acompanhar a evolução do empreendimento após a graduação.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Enviar o instrumento e consolidar o relatório de desempenho',
 'Verificar pontos fortes, fracos, ameaças e oportunidades. Representação gráfica da evolução dos graduados.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Divulgar os resultados do acompanhamento',
 'Divulgar nos meios apropriados o estágio atual, a evolução e os resultados obtidos pelos graduados.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Elaborar e divulgar o portfólio de serviços para graduados',
 'A partir dos serviços sugeridos pelos graduados e daqueles que a incubadora pode oferecer, com foco nas graduadas.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Planejar, executar e registrar os serviços demandados',
 'Receber as demandas, planejar a execução e registrar as evidências do serviço prestado.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Relacionamento com Graduados'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- ===== 1.5 Gerenciamento Básico ============================================
-- Estrutura Organizacional
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Solicitar/atualizar os documentos que comprovam a existência da incubadora',
 'Formalização da incubadora como um programa da instituição mantenedora quando não houver CNPJ próprio.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Criar/atualizar a comprovação da existência da equipe',
 'Ao menos um membro com 40 horas de dedicação à incubadora.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Criar/atualizar o Modelo de Negócios da incubadora',
 'Desenvolver e manter atualizado o Modelo de Negócios da incubadora.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Criar/atualizar o Plano de Ação',
 'Usar o plano de ação como referência na implementação das ações propostas para atingir metas e objetivos.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Arquivar todos os documentos da estrutura organizacional',
 'Documentos assinados e de fácil consulta, pois vários são utilizados por outras práticas-chave.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Estrutura Organizacional'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- Operação da Incubadora
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Elaborar o orçamento anual e o fluxo de caixa previsto',
 'Explicitar os apoios recebidos, as ações e estruturas mantidas com recursos próprios e as estratégias de sustentabilidade.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Realizar os controles financeiros e atualizar o fluxo de caixa realizado',
 'Controle do previsto/realizado das receitas e despesas, tanto financeiras quanto econômicas.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Levantar necessidades e manter o documento de infraestrutura física e tecnológica',
 'Ouvir incubados, graduados, equipe e parceiros. Prever espaços, equipamentos e infraestrutura de comunicação e convivência.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Definir e manter os serviços operacionais',
 'Limpeza, vigilância, manutenção e recepção. Definir periodicidade, horários e formas de acesso.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Elaborar o plano de sustentabilidade e arquivar os documentos da operação',
 'Analisar o orçamento e o fluxo de caixa ao final do ano; arquivar os documentos de forma que permita fácil consulta.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Operação da Incubadora'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.'),

-- Comunicação e Marketing
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'Desenvolver a identidade corporativa',
 'Definir missão, visão e valores; criar logomarca e manual de uso da marca; criar assinaturas de e-mail corporativo.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'Desenvolver e manter o material de comunicação impresso e digital',
 'Peças gráficas: cartões de visita, envelopes, papel timbrado, folder institucional e crachás.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'Elaborar a estratégia de presença digital da incubadora',
 'No início de cada ano, elaborar a estratégia de presença digital da incubadora.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'Executar a estratégia de presença digital',
 'Executar conforme o plano de mídia, em fluxo contínuo.'),
((SELECT MOD_COD FROM MODELOS WHERE NOME = 'Plano Anual CERNE 1 (padrão)'),
 (SELECT PRT_COD FROM PRATICAS WHERE NOME = 'Comunicação e Marketing'),
 'Avaliar a efetividade das ações',
 'Avaliação realizada em conjunto com todas as práticas na reunião anual de avaliação e planejamento das atividades do ano seguinte.');
