-- ============================================================================
-- Seed das ATIVIDADES-PADRÃO da metodologia — CERNE 1 (Nível I)
-- Fonte: Manual CERNE I e II (2023), coluna "Atividade"/"Observações" das
-- tabelas de cada sub-plano ("Meios/Ações") das práticas-chave do Nível I.
--
-- ESPELHO COMPLETO DO MANUAL, por AGRUPAMENTO (sub-plano), SEM deduplicar: cada
-- sub-plano é um fluxo próprio, então passos repetidos entram uma vez em CADA
-- sub-plano onde o Manual os lista. "Quem"/"Quando" NÃO são semeados (vêm no
-- ciclo/planejamento).
--
-- NÃO são semeadas as atividades genéricas de "Registro das evidências da
-- execução" nem de "Avaliação da efetividade das ações praticadas": o sistema
-- já cobre isso por tarefa (evidências anexadas + indicadores). Onde o registro
-- vinha embutido no nome de uma ação ("... e registrar as evidências da
-- execução"), o sufixo foi removido — fica só a ação.
--
-- PRÉ-REQUISITO: rode antes o seed_cerne1_metodologia.sql (PRATICAS_METODOLOGIA
-- e AGRUPAMENTOS). As atividades ligam-se ao agrupamento por (PRT_COD, NOME).
--   SET search_path TO "<schema_do_tenant>";
--   \i seed_cerne1_atividades_metodologia.sql
-- ============================================================================

INSERT INTO ATIVIDADES_METODOLOGIA (PRT_COD, AGR_COD, ORDEM, NOME, OBSERVACOES, POR_EMPREENDIMENTO) VALUES

-- ===== 1.1 Sensibilização ==================================================
-- Sub-plano: Participação em eventos externos
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos externos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 1,
 'Identificar parceiros externos e caso necessário, firmar parcerias para realização de eventos.',
 'A busca de parcerias pode maximizar o evento em termos de participantes e é estratégico na redução dos custos.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos externos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 2,
 'Receber convite.',
 'O processo pode ser iniciado por demanda em fluxo contínuo ou então em datas previstas de acordo com o planejamento semestral.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos externos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 3,
 'Planejar o evento e os conteúdos.',
 'Padronizar os conteúdos utilizados. Utilizar os próprios incubados, graduados e parceiros como sensibilizadores pode ser uma boa estratégia.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos externos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 4,
 'Definir canais de comunicação.',
 'Acompanhar e avaliar os canais utilizados, para assim otimizar os recursos, investindo mais naqueles que trazem melhores resultados.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos externos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 5,
 'Definir e reservar todos os recursos necessários para a execução da ação.',
 'Garantir que os recursos estejam disponíveis dentro das especificações do evento; observar recursos financeiros, de infraestrutura, tecnológicos e de logística, sejam eles internos ou dos parceiros.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos externos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 6,
 'Divulgar e iniciar inscrições para o evento.',
 'Avaliar o meio de divulgação e a inscrição eletrônica podem ser boas práticas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos externos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 7,
 'Participar das ações.',
 'Os registros da ação devem incluir pelo menos o número e perfil das pessoas sensibilizadas, o local, a data, profissional responsável e o conteúdo apresentado. Importante: perguntar se o participante tem interesse em incubar; caso afirmativo, este registro (que também pode ser feito no ato de inscrição) será entrada para a prática-chave qualificação de potenciais empreendedores.', FALSE),
-- Sub-plano: Participação em eventos internos
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 8,
 'Mapear e identificar os eventos internos compatíveis com a sensibilização e difusão para a cultura de inovação e empreendedorismo.',
 'O mapeamento e identificação de eventos compatíveis podem maximizar a sensibilização e é estratégico no que diz respeito ao público-alvo.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 9,
 'Receber convocação/indicação ou negociar a participação no evento.',
 'O processo é iniciado por demanda interna em momentos de fluxo contínuo ou então em datas previstas de acordo com o planejamento semestral.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 10,
 'Planejar o evento e os conteúdos.',
 'Padronizar os conteúdos utilizados. Utilizar os próprios incubados, graduados e parceiros como sensibilizadores pode ser uma boa estratégia.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 11,
 'Definir canais de comunicação.',
 'Acompanhar e avaliar os canais utilizados, para assim otimizar os recursos, investindo mais naqueles que trazem melhores resultados.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 12,
 'Definir e reservar todos os recursos necessários para a execução da ação.',
 'Garantir que os recursos estejam disponíveis dentro das especificações do evento; observar recursos financeiros, de infraestrutura, tecnológicos e de logística.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 13,
 'Divulgar e iniciar inscrições para o evento.',
 'Avaliar o meio de divulgação e a inscrição eletrônica podem ser boas práticas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 14,
 'Realizar ação.',
 'Os registros da ação devem incluir pelo menos o número e perfil das pessoas sensibilizadas, o local, a data, profissional responsável e o conteúdo apresentado. Importante: perguntar se o participante tem interesse em incubar; caso afirmativo, este registro (que também pode ser feito no ato de inscrição) será entrada para a prática-chave qualificação de potenciais empreendedores.', FALSE),
-- Sub-plano: Participação em programas de rádio e televisão
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em programas de rádio e televisão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 15,
 'Receber o convite/pautar a rádio e/ou TV.',
 'Planejar em conjunto com a SUPEC e diretorias da rádio e TV o calendário anual de programas relativos à sensibilização e aproveitar pautas que surgirem fora do planejado.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em programas de rádio e televisão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 16,
 'Definir sensibilizador e assunto.',
 'Padronizar os conteúdos utilizados. Utilizar os próprios incubados e graduados, gestores e pesquisadores como sensibilizadores pode ser uma boa estratégia.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em programas de rádio e televisão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 17,
 'Efetuar a divulgação interna e externa, via mídias sociais.',
 'A prospecção de público para os programas de rádio e TV pode ser feita através das redes sociais do Espaço Empreendedor.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em programas de rádio e televisão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 18,
 'Participar do programa de rádio ou TV.',
 'Apesar do tema proposto, o sensibilizador deverá sempre lembrar de mencionar a incubadora e os serviços ofertados.', FALSE),
-- Sub-plano: Divulgação em mídias sociais
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Divulgação em mídias sociais' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 19,
 'Definir pauta de divulgação.',
 'Decidir os temas a serem abordados com ênfase nos acontecimentos e no plano de comunicação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Divulgação em mídias sociais' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 20,
 'Elaboração do conteúdo/matéria a ser divulgada.',
 'Na criação do conteúdo deve ser considerada a linguagem e identidade visual da Incubadora e o veículo.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Divulgação em mídias sociais' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 21,
 'Revisão e aprovação do conteúdo a ser divulgado.',
 'Observar o conteúdo e a apropriação ao veículo.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Divulgação em mídias sociais' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Sensibilização')), 22,
 'Publicação do conteúdo/matéria nas mídias sociais e/ou site.',
 'O time da publicação é importante para cada tipo de público-alvo e momento.', FALSE),

-- ===== 1.1 Prospecção ======================================================
-- Sub-plano: Participação nas bancas do projetão
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação nas bancas do projetão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 1,
 'Identificar projetos finais de disciplina que oportunizam negócios e soluções inovadoras.',
 'A equipe de Gestão deve, de forma proativa, prospectar possíveis ofertas inovadoras segundo ideias de negócios que poderão impactar futuramente a economia da área de atuação da incubadora, interagindo com os alunos e os centros das disciplinas de empreendedorismo no decorrer do semestre letivo.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação nas bancas do projetão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 2,
 'Contatar os docentes da disciplina que será objeto da prospecção e planejar a ação de prospecção.',
 'O registro deste contato inicial pode ser evidência desta prática. O resultado deste contato é o planejamento da ação de prospecção com definição da periodicidade. Este contato pode incluir mais de um contato virtual e/ou físico.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação nas bancas do projetão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 3,
 'Realizar ação de prospecção no dia da banca final (demoday).',
 'Os registros da ação devem incluir os resultados da execução desta prática-chave.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação nas bancas do projetão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 4,
 'Armazenar as oportunidades de negócios no Banco de Oportunidades.',
 'Registro que comprova a existência do Banco de Oportunidades. Deve-se demonstrar como foi criado e como se alimenta e atualiza este banco de oportunidades. Deve ser de fácil acesso e fácil compreensão.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação nas bancas do projetão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 5,
 'Divulgar as oportunidades prospectadas.',
 'Busca fazer um matchmaking casando ofertantes com demandantes ou vice-versa. Apresentar as oportunidades que possam ser aproveitadas por interessados e que talvez possam se tornar empreendedores da incubadora.', FALSE),
-- Sub-plano: Reuniões com pesquisadores da UFES
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com pesquisadores da UFES' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 6,
 'Identificar grupos de pesquisas e laboratórios com potenciais projetos de inovação com capacidade de geração de negócios.',
 'A equipe de Gestão deve, de forma proativa, prospectar possíveis ofertas inovadoras segundo ideias de negócios que poderão impactar futuramente a economia da área de atuação da incubadora.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com pesquisadores da UFES' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 7,
 'Contatar os grupos de pesquisa e docentes que serão objeto da prospecção e planejar a ação de prospecção.',
 'O registro deste contato inicial pode ser evidência desta prática. O resultado deste contato é o planejamento da ação de prospecção com definição da periodicidade. Este contato pode incluir mais de um contato virtual e/ou físico.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com pesquisadores da UFES' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 8,
 'Prospectar ideias através de reuniões e rodas de conversas, previamente agendadas com a Equipe Gestora.',
 'Os registros da ação devem incluir os resultados da execução desta prática-chave.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com pesquisadores da UFES' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 9,
 'Coletar os registros por meio de lista de presença, fotos ou mídias digitais. Armazenar a oportunidade de negócios no Banco de Oportunidades.',
 'Registro que comprova a existência do Banco de Oportunidades. Deve-se demonstrar como foi criado e como se alimenta e atualiza este banco de oportunidades. Deve ser de fácil acesso e fácil compreensão.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com pesquisadores da UFES' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 10,
 'Divulgar as ofertas prospectadas.',
 'Busca fazer um matchmaking casando ofertantes com demandantes ou vice-versa. Apresentar as oportunidades que possam ser aproveitadas por interessados e que talvez possam se tornar empreendedores da incubadora.', FALSE),
-- Sub-plano: Reuniões com os setores público e privado
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com os setores público e privado' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 11,
 'Identificar parceiros/atores com demandas/gargalos setoriais tanto no setor público quanto privado.',
 'Ação proativa; é corpo a corpo. A equipe de gestão deve buscar oportunidades de negócio. Pode convidar empresas para que exponham seus problemas e/ou necessidades, que poderão ser ideias de negócios.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com os setores público e privado' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 12,
 'Definir canais de comunicação com os parceiros.',
 'Acompanhar e avaliar os canais utilizados, para assim otimizar os recursos, investindo mais naqueles que trazem melhores resultados.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com os setores público e privado' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 13,
 'Contatar o parceiro que será objeto da prospecção e planejar a ação de prospecção.',
 'O registro deste contato inicial pode ser evidência desta prática. O resultado deste contato é o planejamento da ação de prospecção com definição da periodicidade. Este contato pode incluir mais de um contato virtual e/ou físico.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com os setores público e privado' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 14,
 'Realizar ação de prospecção.',
 'Os registros da ação devem incluir os resultados da execução desta prática-chave.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com os setores público e privado' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 15,
 'Armazenar a oportunidade de negócios no Banco de Oportunidades.',
 'Registro que comprova a existência do Banco de Oportunidades. Deve-se demonstrar como foi criado e como se alimenta e atualiza este banco de oportunidades. Deve ser de fácil acesso e fácil compreensão.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Reuniões com os setores público e privado' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 16,
 'Divulgar as oportunidades prospectadas.',
 'Busca fazer um matchmaking casando ofertantes com demandantes ou vice-versa. Apresentar as oportunidades que possam ser aproveitadas por interessados e que talvez possam se tornar empreendedores da incubadora.', FALSE),
-- Sub-plano: Curadoria em editais e chamadas
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Curadoria em editais e chamadas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 17,
 'Identificar editais e/ou chamadas com demandas e possibilidades de negócios.',
 'Ação proativa; é corpo a corpo. A equipe de gestão deve buscar oportunidades de negócio em editais e chamadas publicadas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Curadoria em editais e chamadas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 18,
 'Realizar a curadoria das chamadas e editais de acordo com a vocação da incubadora, e em consonância com os negócios incubados, graduados ou prospectados.',
 'Acompanhar e avaliar os canais utilizados, para assim otimizar os recursos, investindo mais naqueles que trazem melhores resultados.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Curadoria em editais e chamadas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 19,
 'Realizar ação de prospecção.',
 'Os registros da ação devem incluir os resultados da execução desta prática-chave.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Curadoria em editais e chamadas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 20,
 'Armazenar a oportunidade de negócios no Banco de Oportunidades.',
 'Registro que comprova a existência do Banco de Oportunidades. Deve-se demonstrar como foi criado e como se alimenta e atualiza este banco de oportunidades. Deve ser de fácil acesso e fácil compreensão.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Curadoria em editais e chamadas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Prospecção')), 21,
 'Divulgar as oportunidades prospectadas.',
 'Busca fazer um matchmaking casando ofertantes com demandantes ou vice-versa. Apresentar as oportunidades que possam ser aproveitadas por interessados e que talvez possam se tornar empreendedores da incubadora.', FALSE),

-- ===== 1.1 Qualificação de Potenciais Empreendedores =======================
-- Sub-plano: Participação nas disciplinas da universidade
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação nas disciplinas da universidade' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 1,
 'Mapear e identificar as disciplinas de empreendedorismo e inovação compatíveis com a qualificação de potenciais empreendedores.',
 'Padronizar os conteúdos utilizados. Utilizar a própria equipe de gestão, os incubados e/ou graduados como facilitadores pode ser uma boa estratégia. Se utilizar ações de terceiros, demonstrar claramente a parceria e que a mesma está em sintonia com os objetivos da incubadora.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação nas disciplinas da universidade' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 2,
 'Negociar com os docentes a participação e o conteúdo a ser desenvolvido.',
 'Negociar os quesitos a serem abordados na ótica de otimização do aprendizado, em complemento à disciplina.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação nas disciplinas da universidade' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 3,
 'Definir e reservar todos os recursos necessários para a execução da ação.',
 'Recursos financeiros, de infraestrutura, tecnológicos e de logística.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação nas disciplinas da universidade' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 4,
 'Realizar ação.',
 'Os registros da ação devem incluir pelo menos o número e perfil das pessoas qualificadas, o local, a data, profissional responsável e o conteúdo apresentado.', FALSE),
-- Sub-plano: Participação em eventos internos
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 5,
 'Mapear e identificar os eventos internos compatíveis para a qualificação de potenciais empreendedores.',
 'O mapeamento e identificação de eventos compatíveis podem maximizar a qualificação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 6,
 'Receber convocação/indicação ou negociar a participação no evento.',
 'O processo é iniciado por demanda interna em momentos de fluxo contínuo ou então em datas previstas de acordo com o planejamento semestral.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 7,
 'Planejar o evento, os instrumentos e os conteúdos de qualificação.',
 'Padronizar os conteúdos utilizados. Utilizar os próprios incubados, graduados e parceiros como sensibilizadores pode ser uma boa estratégia.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 8,
 'Definir e reservar todos os recursos necessários para a execução da ação.',
 'Garantir que os recursos estejam disponíveis dentro das especificações do evento; observar recursos financeiros, de infraestrutura, tecnológicos e de logística.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 9,
 'Divulgar e iniciar inscrições para o evento.',
 'Avaliar o meio de divulgação e a inscrição eletrônica podem ser boas práticas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Participação em eventos internos' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Qualificação de Potenciais Empreendedores')), 10,
 'Realizar ação.',
 'Os registros da ação devem incluir pelo menos o número e perfil das pessoas sensibilizadas, o local, a data, profissional responsável e o conteúdo apresentado. Importante: perguntar se o participante tem interesse em incubar; caso afirmativo, este registro (que também pode ser feito no ato de inscrição) será entrada para a prática-chave qualificação de potenciais empreendedores.', FALSE),

-- ===== 1.2 Recepção de Propostas ===========================================
-- Sub-plano: Edital com formulário online de submissão de propostas
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Edital com formulário online de submissão de propostas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas')), 1,
 'Planejar processo de Seleção.',
 'Definir o tipo de chamada, etapas do processo, os formulários e as ferramentas para recepção de propostas, formas de submissão. Definir os critérios de avaliação. Definir como e quando a chamada será lançada.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Edital com formulário online de submissão de propostas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas')), 2,
 'Elaborar instrumento de chamada / Edital.',
 'Colocar nele todo o definido no planejamento anterior; deixar claras as etapas do processo, os instrumentos/documentos a serem apresentados, os critérios de avaliação, a forma de apresentar as propostas e o cronograma completo.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Edital com formulário online de submissão de propostas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas')), 3,
 'Definir canais de comunicação e divulgação.',
 'Acompanhar e avaliar os canais utilizados, para assim otimizar os recursos, investindo mais naqueles que trazem melhores resultados.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Edital com formulário online de submissão de propostas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas')), 4,
 'Divulgar chamada de candidatos à incubação.',
 'Avaliar o meio de divulgação é uma boa prática.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Edital com formulário online de submissão de propostas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas')), 5,
 'Receber propostas.',
 'Ter todas as propostas registradas/protocoladas como recebidas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Edital com formulário online de submissão de propostas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas')), 6,
 'Efetuar a homologação das propostas.',
 'Avaliar, de acordo com a chamada, se cumpriram os requisitos formais da submissão, não avaliando aqui o conteúdo da proposta em si.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Edital com formulário online de submissão de propostas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas')), 7,
 'Informar e registrar aquelas propostas eliminadas.',
 'Todas as propostas que não forem aceitas por não cumprir requisitos da submissão serão registradas e eliminadas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Edital com formulário online de submissão de propostas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Recepção de Propostas')), 8,
 'Divulgar resultado da recepção de propostas.',
 'Registrar e protocolar aquelas propostas OK e que serão avaliadas na próxima prática-chave.', FALSE),

-- ===== 1.2 Avaliação =======================================================
-- Sub-plano: Avaliação em duas etapas
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Avaliação em duas etapas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação')), 1,
 'Planejar a Avaliação.',
 'A partir do Planejamento do processo de seleção definido na prática-chave recepção de propostas, e da chamada/Edital, definir em maiores detalhes todas as ações do procedimento de avaliação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Avaliação em duas etapas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação')), 2,
 'Convidar Avaliadores.',
 'Definir o meio de contato e convite, levando em consideração expertise e perfil do potencial avaliador; enviar informações sobre o processo de avaliação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Avaliação em duas etapas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação')), 3,
 'Formar a Banca de Avaliação.',
 'Convocar os membros respeitando os prazos previstos na chamada/Edital. Mínimo dois integrantes.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Avaliação em duas etapas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação')), 4,
 'Preparar a Avaliação e alinhar com a banca de avaliação, entregando instrumentos de avaliação.',
 'Seria interessante fazer uma reunião com os avaliadores para mostrar as expectativas e objetivos da incubadora, processo de seleção, critérios de avaliação, pesos dos mesmos, etc. Preparar e entregar todos os documentos e formulários necessários para avaliação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Avaliação em duas etapas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação')), 5,
 'Enviar propostas à Banca e promover uma leitura criteriosa.',
 'Confirmar que receberam as propostas, reforçar os critérios e os prazos. Importante: comprovar que todas as propostas recebidas serão avaliadas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Avaliação em duas etapas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação')), 6,
 'Executar as etapas de avaliação previstas na chamada/Edital.',
 'Seguir rigorosamente todo o processo planejado e definido na chamada/edital: cronogramas, etapas, instrumentos utilizados.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Avaliação em duas etapas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação')), 7,
 'Consolidar as avaliações da Banca.',
 'Tabular todas as avaliações, promover consenso entre os membros da banca, elaborar lista de aprovados, de reprovados e os motivos da reprovação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Avaliação em duas etapas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação')), 8,
 'Entrar em contato com os proponentes, informar resultados e motivos de propostas não aprovadas.',
 'Após a consolidação, a incubadora deve entrar em contato com os proponentes, antes de tornar público o resultado, para informá-los se o projeto foi ou não aprovado e justificar o motivo da não aprovação, orientando-os sobre possíveis melhorias na proposta.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Avaliação em duas etapas' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Avaliação')), 9,
 'Divulgar resultado do processo seletivo.',
 'Fazer lista para oficializar o resultado da seleção, divulgando nos meios apropriados.', FALSE),

-- ===== 1.2 Contratação =====================================================
-- Sub-plano: Assinatura do contrato de incubação
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Assinatura do contrato de incubação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação')), 1,
 'Planejar a Contratação definindo datas e convidando as autoridades e empreendimentos selecionados.',
 'A partir do Planejamento do processo de seleção definido na prática-chave recepção de propostas, e da chamada/Edital, definir em maiores detalhes todas as ações do procedimento de contratação. Verificar cronograma.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Assinatura do contrato de incubação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação')), 2,
 'Realizar encontro/reunião para orientação sobre contratação e incubação.',
 'Explicar o processo de contratação e de incubação. Entregar lista de documentos necessários para contratação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Assinatura do contrato de incubação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação')), 3,
 'Receber todos os documentos para contratação.',
 'Verificar se todos os documentos solicitados foram entregues e se estão em conformidade.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Assinatura do contrato de incubação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação')), 4,
 'Elaborar Contrato e envio aos empreendedores e ao setor jurídico.',
 'De acordo com o tipo de processo de incubação (pré, virtual, residente). Instrumento formal que estabeleça as regras e responsabilidades entre o candidato e a incubadora. Deve conter todas as condições da relação entre o empreendedor e a incubadora.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Assinatura do contrato de incubação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação')), 5,
 'Revisão jurídica e por parte dos empreendedores dos contratos.',
 'Revisar, tirar as dúvidas e chegar a um acordo para assinatura. Confirmar data de assinatura.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Assinatura do contrato de incubação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação')), 6,
 'Realizar evento de Assinatura dos contratos.',
 'Grande momento; divulgar amplamente, envolver parceiros, incubados, graduados, equipe da incubadora e mantenedora. Pode-se entregar certificado de incubado.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Assinatura do contrato de incubação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Contratação')), 7,
 'Realizar integração dos novos incubados.',
 'Apresentar incubadora, equipe, outros incubados, visita guiada aos ambientes. Boa oportunidade para ampliar a interação.', FALSE),

-- ===== 1.3 Planejamento do Empreendimento ==================================
-- Sub-plano: Planejamento do desenvolvimento do empreendimento
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Planejamento do desenvolvimento do empreendimento' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento')), 1,
 'Identificar se é planejamento inicial (A) ou atualização de planejamento já existente (B).',
 'Importante verificar no início do procedimento se é o planejamento inicial de um novo incubado ou a atualização do planejamento de um incubado após executar monitoramento. O processo de planejamento deve ser sistemático; não deve ser feito apenas na entrada da empresa/empreendedor na incubadora.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Planejamento do desenvolvimento do empreendimento' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento')), 2,
 '(A) Definir e elaborar os instrumentos e modelos que auxiliarão o planejamento e o monitoramento.',
 'O formato e a profundidade do plano são definidos pela incubadora. Podem ser utilizadas diferentes metodologias e modelos de planos. Aqui também devem ser definidos os instrumentos que serão utilizados no monitoramento, pois esta dupla planejamento/acompanhamento é definida aqui.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Planejamento do desenvolvimento do empreendimento' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento')), 3,
 '(A) Marcar encontro inicial com empreendedor para alinhamento e conhecimento dos instrumentos.',
 'O responsável deve agendar reunião com as empresas recém-incubadas para realização do alinhamento, explicar a metodologia de planejamento, seus instrumentos e modelos de documentos nos 5 eixos.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Planejamento do desenvolvimento do empreendimento' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento')), 4,
 'Elaborar o Planejamento.',
 'O planejamento do empreendimento deve estabelecer ações que iniciam um ciclo de desenvolvimento. A gestão do planejamento deve ser do empreendedor. O planejamento deve conter um conjunto de estratégias, metas e ações para o curto, médio e longo prazo.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Planejamento do desenvolvimento do empreendimento' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento')), 5,
 'Aprovar o planejamento proposto.', NULL, TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Planejamento do desenvolvimento do empreendimento' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento')), 6,
 '(B) Utilizar monitoramento para atualizar o planejamento.',
 'Os planos devem ser atualizados de acordo com o desenvolvimento do negócio identificado no monitoramento.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Planejamento do desenvolvimento do empreendimento' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Planejamento do Empreendimento')), 7,
 '(B) Aprovar planejamento modificado e iniciar acompanhamento da execução.',
 'A atualização dos planos alimenta o desenvolvimento de ações da incubadora. Os planos devem ser utilizados como ferramentas de gestão.', TRUE),

-- ===== 1.3 Agregação de Valor ==============================================
-- Sub-plano: Ações de agregação de valor
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Ações de agregação de valor' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor')), 1,
 'A partir dos planejamentos dos incubados, elaborar o Plano Anual de Agregação de Valor da Incubadora.',
 'O plano anual deve ser elaborado de forma coletiva, envolvendo toda a equipe do Espaço Empreendedor, sua Gerência e a equipe da Diretoria de Inovação Tecnológica, com base no planejamento estratégico e na metodologia de boas práticas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Ações de agregação de valor' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor')), 2,
 'A partir do Plano Anual de Agregação de Valor, identificar a ação de agregação de valor a ser executada (a que a incubadora irá oferecer).',
 'Há dois momentos em que a incubadora deve decidir quais ações de agregação de valor devem ser desenvolvidas para as empresas: 1. no momento do planejamento inicial; 2. sempre após um monitoramento, pois os planejamentos podem ser atualizados e, por isso, deve ser novamente executado este procedimento para verificar se há novas necessidades de ações de agregação de valor.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Ações de agregação de valor' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor')), 3,
 'Identificar e contatar os prestadores do serviço de agregação de valor.',
 'Podem ser internos, externos ou identificar parceiros que possam executar estas ações de agregação de valor.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Ações de agregação de valor' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor')), 4,
 'Realizar a ação de agregação de valor.',
 'Os registros da ação devem incluir todas as informações para identificar a execução da ação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Ações de agregação de valor' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Agregação de Valor')), 5,
 'Atualizar os planos dos incubados participantes.',
 'Atualizar em cada planejamento do incubado a ação realizada, com os resultados obtidos.', FALSE),

-- ===== 1.3 Monitoramento do Empreendimento =================================
-- Sub-plano: Monitoramento com instrumento próprio
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Monitoramento com instrumento próprio' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento')), 1,
 'Identificar e definir os especialistas que farão o monitoramento (equipe de gestão ou mentor ou professor).',
 'Podem ser internos, externos ou identificar parceiros que possam executar a consultoria. Quando utilizar profissionais externos à incubadora, esta relação deve ser formalizada.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Monitoramento com instrumento próprio' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento')), 2,
 'Elaborar, verificar e divulgar Agenda de Monitoramentos.',
 'A partir dos planejamentos dos incubados, elaborar cronograma de monitoramento.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Monitoramento com instrumento próprio' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento')), 3,
 'Entrevista/Encontro com os empreendedores.',
 'Nesta reunião, utilizar os instrumentos de monitoramento para coletar as informações referentes ao estágio dos 5 eixos. É uma verificação do previsto vs. realizado no planejamento do empreendimento.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Monitoramento com instrumento próprio' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento')), 4,
 'Analisar situação e evolução da empresa, segundo metas e critérios do planejamento.',
 'Verificar o desempenho do empreendimento em relação ao planejado nos 5 eixos.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Monitoramento com instrumento próprio' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento')), 5,
 'Avaliar resultados obtidos.',
 'Avaliar os resultados de acordo com as metas previstas para a etapa e estágio atual do empreendimento.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Monitoramento com instrumento próprio' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento')), 6,
 'Elaborar relatório do monitoramento.',
 'Utilizar instrumento para elaborar relatório com todas as considerações do monitoramento, como por exemplo recomendação para graduação, sugestões para replanejamento (com novas ações, prazos e metas, com justificativas) ou recomendação de desligamento.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Monitoramento com instrumento próprio' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento')), 7,
 'Reunião com empreendedor para avaliar relatório.',
 'Análise das informações fornecidas pelo relatório, levando em consideração o tipo de negócio e o estágio de incubação.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Monitoramento com instrumento próprio' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento')), 8,
 'Atualizar os planos dos incubados participantes.',
 'Atualizar em cada planejamento do incubado as informações referentes ao monitoramento, resultados obtidos, metas atingidas, não atingidas e próximos passos.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Monitoramento com instrumento próprio' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Monitoramento do Empreendimento')), 9,
 'Verificar se o empreendimento está pronto para graduar, para continuar incubado ou para ser desligado.',
 'Se atingiu o grau de maturidade para graduar, ir para a prática-chave graduação; se vai continuar incubado, ir para a prática-chave planejamento para atualizar seu planejamento a partir deste monitoramento; se não vai continuar incubado, fazer o desligamento.', TRUE),

-- ===== 1.4 Graduação =======================================================
-- Sub-plano: Evento de graduação
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Evento de graduação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação')), 1,
 'Identificar no monitoramento e no Plano Anual de Graduações as empresas incubadas que estão aptas para graduar.',
 'A partir dos planejamentos atualizados pelos monitoramentos, identificar as empresas que estarão aptas para graduar no próximo ciclo.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Evento de graduação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação')), 2,
 'Avaliar e confirmar condições para a mudança de status da empresa.',
 'A partir da recomendação de graduação apontada no último monitoramento e registrada no planejamento da incubada, avaliar o empreendimento para graduação e gerar um Relatório de Graduação.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Evento de graduação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação')), 3,
 'Preparar empresa para Graduação.',
 'Reunião para esclarecimentos. Auxiliar a empresa na estimativa do impacto financeiro e econômico da graduação. Auxiliar na procura de espaço físico para sua instalação como graduada.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Evento de graduação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação')), 4,
 'Realizar Procedimentos administrativos para a Graduação.',
 'Atualizar todos os registros internos da incubadora (de incubada para graduada). Fazer vistoria da sala e móveis.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Evento de graduação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação')), 5,
 'Oficializar Juridicamente a Graduação.',
 'Preparar e assinar o termo de encerramento de graduação. Preparar contrato de associado graduado. Devolução de chaves.', TRUE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Evento de graduação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação')), 6,
 'Planejar Cerimônia de Graduação.',
 'Identificar a mesa de honra, convidar, confeccionar certificados de graduação, elaborar convite eletrônico e/ou impresso. Identificar disponibilidade financeira para definir o tipo de evento a ser realizado.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Evento de graduação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação')), 7,
 'Divulgar Cerimônia de graduação.',
 'Solicitar à assessoria de comunicação a divulgação. Enviar os convites. Avaliar meios de divulgação. Verificar pessoas a serem convidadas para graduação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Evento de graduação' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Graduação')), 8,
 'Realizar a Cerimônia de graduação.',
 'Na cerimônia deverão ser convidadas autoridades da Instituição e do mercado e, se possível, clientes e parceiros das empresas graduadas.', FALSE),

-- ===== 1.4 Relacionamento com Graduados ====================================
-- Sub-plano: Acompanhamento da evolução do desempenho dos graduados
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Acompanhamento da evolução do desempenho dos graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 1,
 'Elaborar/atualizar instrumentos do acompanhamento do graduado.',
 'O formato e a profundidade do acompanhamento são definidos pela incubadora. Podem ser utilizadas diferentes metodologias e modelos. Importante acompanhar a evolução do empreendimento após a sua graduação.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Acompanhamento da evolução do desempenho dos graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 2,
 'Enviar instrumento aos graduados.', NULL, FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Acompanhamento da evolução do desempenho dos graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 3,
 'Receber instrumento preenchido e consolidar num relatório de desempenho dos graduados.',
 'Verificar o desempenho do empreendimento em relação ao tempo transcorrido. Verificar pontos fortes, fracos, ameaças e oportunidades. Representação gráfica da evolução dos graduados. Utilizar instrumento para elaborar relatório com todas as considerações do acompanhamento, como por exemplo recomendação para novos serviços, oportunidades de parcerias, etc.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Acompanhamento da evolução do desempenho dos graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 4,
 'Divulgar resultados do acompanhamento.',
 'Divulgar nos meios apropriados o estágio atual, a evolução e os resultados obtidos pelos graduados.', FALSE),
-- Sub-plano: Oferta de serviços especializados para graduados
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Oferta de serviços especializados para graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 5,
 'Identificar nas respostas do formulário os serviços sugeridos pelos graduados.',
 'Elaborar mix de serviços, com foco nas graduadas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Oferta de serviços especializados para graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 6,
 'Identificar quais serviços podem ser oferecidos pela incubadora.', NULL, FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Oferta de serviços especializados para graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 7,
 'Divulgar portfólio de serviços para graduados e empresas em geral.',
 'Divulgação ampla.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Oferta de serviços especializados para graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 8,
 'Receber demandas por execução de serviços.',
 'Daqui em diante é outra linha do tempo.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Oferta de serviços especializados para graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 9,
 'Planejar a execução do serviço.', NULL, FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Oferta de serviços especializados para graduados' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Relacionamento com Graduados')), 10,
 'Executar o serviço.', NULL, FALSE),

-- ===== 1.5 Estrutura Organizacional ========================================
-- Sub-plano: Instrumentos jurídicos e equipe de gestão
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Instrumentos jurídicos e equipe de gestão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional')), 1,
 'Solicitar/atualizar documentos que comprovam existência da incubadora.',
 'Caso a incubadora não tenha CNPJ próprio, deve haver um documento que comprove sua existência e vinculação com a entidade gestora/mantenedora. Formalização da incubadora como um programa da instituição mantenedora.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Instrumentos jurídicos e equipe de gestão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional')), 2,
 'Criar/atualizar comprovação da existência da equipe.',
 'Um membro com 40 horas de dedicação à incubadora.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Instrumentos jurídicos e equipe de gestão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional')), 3,
 'Criar/atualizar Modelo de Negócios da Incubadora.',
 'Desenvolver um Modelo de Negócios da incubadora, mantendo-o atualizado.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Instrumentos jurídicos e equipe de gestão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional')), 4,
 'Criar/atualizar Plano de Ação.',
 'Utilizar o plano de ação como referência na implementação das ações propostas para atingir metas e objetivos.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Instrumentos jurídicos e equipe de gestão' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Estrutura Organizacional')), 5,
 'Arquivar todos os documentos da Estrutura Organizacional.',
 'Escolher os meios de armazenamento. Lembrar que os documentos devem estar assinados. A escolha do meio de arquivamento deve permitir fácil consulta, pois vários destes documentos são utilizados por outras práticas-chave.', FALSE),

-- ===== 1.5 Operação da Incubadora ==========================================
-- Sub-plano: Gestão financeira da incubadora
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Gestão financeira da incubadora' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 1,
 'No início de cada ano, elaborar o Orçamento Anual e o Fluxo de Caixa (previsto).',
 'Elaborar orçamento, fluxo de caixa e plano de sustentabilidade. Devem ser explicitados todos os apoios recebidos, as ações e estruturas mantidas com recursos próprios e as estratégias para garantir a sustentabilidade.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Gestão financeira da incubadora' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 2,
 'Mensalmente, fazer todos os controles financeiros e atualizar o fluxo de caixa com o realizado.',
 'Atualizar o fluxo de caixa semanalmente ou mensalmente com controle do previsto/realizado. A incubadora precisa ter um controle sobre as receitas e despesas, tanto financeiras quanto econômicas.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Gestão financeira da incubadora' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 3,
 'No final do ano, fazer uma análise do orçamento e do fluxo de caixa e, a partir desta análise, elaborar o plano de sustentabilidade financeira para o próximo ano.', NULL, FALSE),
-- Sub-plano: Gestão da infraestrutura física e tecnológica
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Gestão da infraestrutura física e tecnológica' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 4,
 'Levantar necessidades de Infraestrutura Física e Tecnológica.',
 'Ouvir incubados, graduados, equipe de gestão e parceiros sobre a adequação das atuais instalações físicas e tecnológicas e novas necessidades.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Gestão da infraestrutura física e tecnológica' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 5,
 'Elaborar/Atualizar Documento descrevendo Infraestrutura Física e Tecnológica.',
 'Espaços para empreendimentos, espaços comuns, espaços para reuniões e eventos, área para convivência, equipamentos para aluguel, infraestrutura de comunicação (internet, telefone etc.). Importante prever área de convivência (cafezinho) e área para showroom.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Gestão da infraestrutura física e tecnológica' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 6,
 'Mensalmente, verificar se a infraestrutura física e tecnológica está de acordo com as atividades desenvolvidas na incubadora.', NULL, FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Gestão da infraestrutura física e tecnológica' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 7,
 'Anualmente, fazer as adequações previstas na infraestrutura física e tecnológica.', NULL, FALSE),
-- Sub-plano: Disponibilização de serviços operacionais
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Disponibilização de serviços operacionais' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 8,
 'Definir os Serviços Operacionais necessários para a incubadora.',
 'Definir tipo de limpeza, tipo de vigilância, tipos necessários de manutenção e necessidades e atividades na recepção da incubadora.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Disponibilização de serviços operacionais' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 9,
 'Atualizar o documento que descreve os serviços operacionais.',
 'Definir periodicidade do serviço. Tipo de vigilância, horários da vigilância, formas de acesso, uso de crachá, leitoras de digitais, etc. Tipos de equipamentos para manutenção preventiva e para manutenção corretiva.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Disponibilização de serviços operacionais' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 10,
 'Mensalmente, verificar se os serviços operacionais estão sendo oferecidos de acordo com o previsto.', NULL, FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Disponibilização de serviços operacionais' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Operação da Incubadora')), 11,
 'Arquivar todos os documentos da Operação da Incubadora.',
 'Escolher os meios de armazenamento. A escolha do meio de arquivamento deve permitir fácil consulta, pois vários destes documentos são utilizados por outras práticas-chave.', FALSE),

-- ===== 1.5 Comunicação e Marketing =========================================
-- Sub-plano: Material de comunicação impresso e digital
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Comunicação e Marketing'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Material de comunicação impresso e digital' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Comunicação e Marketing')), 1,
 'Desenvolver identidade corporativa.',
 'Definir missão, visão e valores; criar logomarca e manual de uso da marca; criar assinaturas de e-mail. A incubadora preocupa-se com a formatação das mensagens enviadas através de seu e-mail corporativo.', FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Comunicação e Marketing'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Material de comunicação impresso e digital' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Comunicação e Marketing')), 2,
 'Desenvolver e manter atualizado material de comunicação impresso e digital.',
 'Desenvolver peças gráficas: cartões de visita, envelopes, papel timbrado, folder institucional, crachás.', FALSE),
-- Sub-plano: Estratégia de presença digital da incubadora
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Comunicação e Marketing'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Estratégia de presença digital da incubadora' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Comunicação e Marketing')), 3,
 'No início de cada ano, elaborar a estratégia de presença digital da incubadora.', NULL, FALSE),
((SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Comunicação e Marketing'),
 (SELECT AGR_COD FROM AGRUPAMENTOS WHERE NOME = 'Estratégia de presença digital da incubadora' AND PRT_COD = (SELECT PRT_COD FROM PRATICAS_METODOLOGIA WHERE NOME = 'Comunicação e Marketing')), 4,
 'Executar a estratégia de presença digital.', NULL, FALSE);
